### ISSUE TITLE
Use in real-time, non-x86 environment

### ISSUE THREAD

**Issue by giacomini** [hioa-cs/IncludeOS#1029]
After some time spent working on a C application for a space mission, I miss the power of C++. I'm then thinking about playing with C++ from the ground up, trying IncludeOS. The environment however is based on a non-x86 architecture (currently SPARC) and, maybe more importantly, requires real-time guarantees. I'm not asking of course that you implement those requirements, I just would like to know if you feel the design of IncludeOS could accomodate them.

**Comment by ingve** [comment]
Support for non-x86 architectures is certainly on the roadmap, with ARM as the most likely candidate in the immediate future. There hasn't been a lot of demand for SPARC support, but once the hardware/architecture specific parts gets isolated (or abstracted into a HAL) it will obviously also be easier to add support for other architectures, like SPARC.

There are no real-time specific facilities in IncludeOS yet. Do you have hard or soft real-time requirements in mind?

**Comment by giacomini** [comment]
I'm afraid hard real-time is needed. Not that I'm an expert in the field, but if you give me some hints on where to look in the code, I can try to form an idea myself. Thanks.

**Comment by alfred-bratterud** [comment]
Hi @giacomini I'm no expert on real-time either, but here are some observations. 
* In general I'm interested in the topic and would like to be able to provide optional support for realtime guarantees, at least to a subset of the expected events (e.g. certain I/O events such as timers). 
*  We do use a high resolution deadline timer on x86 (APIC timer) which is guaranteed to trigger before *n* cycles have passed. However, the most common (and recommended) way of assigning callbacks to interrupts is to simply "[subscribe](https://github.com/hioa-cs/IncludeOS/blob/dev/src/drivers/virtionet.cpp#L167)" to them. That means they'll get deferred and handled whenever the OS is done with whatever it was doing, before getting picked up by the [event loop](https://github.com/hioa-cs/IncludeOS/blob/dev/src/kernel/irq_manager.cpp#L218). E.g. not realtime. However, you can also create context switching interrupt handlers like we do with the [stack sampler](https://github.com/hioa-cs/IncludeOS/blob/dev/src/kernel/profile.cpp#L97). One possible extension to IncludeOS would be to add context switching interrupt handlers, for instance using [ucontext](https://github.com/hioa-cs/IncludeOS/blob/dev/test/posix/integration/ucontext/service.cpp), and allow the user to specify whether a subscription to an event should happen in the preempted context (e.g. real time) or not. 
* Assuming you can manage with a single CPU and no threads, in general when a callback actually does get called, you do have a guarantee that it will run until it's done, only interrupted by, well, interrupts, which will essentially only result in a flag being set atomically. 

Again, I'm no expert whatsoever, but interested in the topic. Please feel free to drop me a line if you have any further questions, or if you can educate me on the matter :-)

**Comment by giacomini** [comment]
Thanks for the hints. I'll think about it and let you know.

Merry Christmas and Happy New Year :-)
