### ISSUE TITLE
Nasm not detected on compile

### ISSUE THREAD

**Issue by themodder666** [hioa-cs/IncludeOS#1053]
I'm getting the following error when attempting to run install.sh on the dev branch

-- The ASM_NASM compiler identification is unknown
-- Found assembler: /usr/bin/nasm
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1095 (file):
  file problem creating directory: /usr/local/includeos/bin
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2411 (_ep_set_directories)
  CMakeLists.txt:97 (ExternalProject_Add)

I've checked that there's nothing wrong with the NASM installation, is this a cmake issue?

**Comment by ingve** [comment]
What OS/version are you running?

**Comment by fwsGonzo** [comment]
The error is `problem creating directory: /usr/local/includeos/bin`, so you most likely didn't have privileges. Either install with sudo, or choose another install path, such as somewhere in your home directory.

**Comment by themodder666** [comment]
I'm stupid; you're correct. Issue resolved.
