### ISSUE TITLE
DNS request do not return the IP answer

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#1068]
@ingve mind adding some of your debug output in this issue?

**Comment by ingve** [comment]
When using the http client to get() the url `http://api.ipify.org/` the get request fails with `Unable to resolve host`.

By placing a call to request.print() in `DNSClient::resolve` right after `request.parseResponse(data);`, the following is printed:

```
1 questions
 2 answers
 0 authoritative servers
 0 additional records

Name: .piipifyorg has alias: api.ipify.org.herokudns.com
Name: api.ipify.org.herokudns.com has IPv4 address: 184.72.248.171
```

**Comment by ingve** [comment]
If I try to use the api.ipify.org.herokudns.com address in the call to get(), the following is printed by request.print():

```
1 questions
 0 answers
 1 authoritative servers
 0 additional records

Name:  has unknown resource type: 6
```

**Comment by AndreasAakesson** [comment]
So the problem is it can be many answer, and not all of them has to be IP4 addresses (but aliases etc). `getFirstIP4()` returns the first *answer*, not the first **IP4** answer.
