### ISSUE TITLE
Allow users to change stack and heap sizes

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#107]
Since  various services have very different needs for stack- heap- and service sizes, I don't think there's any "one solution fits all" here, due to the memory hole at around 0xa0000. However, I think we can automatically decide the _locations_ of these, based on the sizes.
- The stack location is now set in the bootloader (`kernel_stack`). I think we should always place it in front of the service, allowing it to grow towards 0. 
-  To calculate all locations, we need to consider these variables:
  - Maximum heap size (_heap_max_)
  - Maximum stack size (_stack_max_) 
  - Service size, including .bss (_srv_size_).
- If _stack_max <= 0xa0000_ we'll place it at address _stack_max_. 
  - Now whichever of heap and service that fits in the same range, can be placed there, prioritizing the service first, since it's constant sized.
- Otherwise I guess at _stack_max + 0x100000_. 
  - Again, whichever of heap and service that now fits below 0xa0000 can be placed there, prioritizing the service first.

**Caveat:** It seems we also have to avoid overwriting the bootloader. I got Qemu restart whenever I tried to overwrite it.

In any case, required physical memory for the qemu process can be derived from these. It will be:
- 1 MB if everything fits below the hole
- Otherwise 1 MB + the size of whichever of the three that has to be placed outside.

**Comment by fwsGonzo** [comment]
This is for the most part solved. The only remaining problem now is that memory from Cmakelists isn't necessarily linked to the value provided to the VM. That is however another issue. Closing this.
