### ISSUE TITLE
Undefined symbols on openssl linkage

### ISSUE THREAD

**Issue by themodder666** [hioa-cs/IncludeOS#1077]
I successfully compiled openssl, but when i try to link it to the service, I get the following error.
`../libcrypto.a(mem_sec.o): In function `CRYPTO_secure_malloc_init':
../../../mnt/c/data/openssl/crypto/mem_sec.c:(.text+0x145): undefined reference to `sysconf'
../../../mnt/c/data/openssl/crypto/mem_sec.c:(.text+0x210): undefined reference to `mprotect'
../../../mnt/c/data/openssl/crypto/mem_sec.c:(.text+0x23f): undefined reference to `mprotect'
../../../mnt/c/data/openssl/crypto/mem_sec.c:(.text+0x258): undefined reference to `mlock'
../libcrypto.a(rand_unix.o): In function `RAND_poll':
../../../mnt/c/data/openssl/crypto/rand/rand_unix.c:(.text+0x293): undefined reference to `getuid'`
Are these functions scheduled to be implemented?

**Comment by fwsGonzo** [comment]
sysconf is easy, and getuid can just return whatever value, eg. 0. `mprotect()` and mlock requires paging, but we can always just stub them just to get it to compile

so, I think you can just go ahead and stub them for now. maybe make sure to figure out what openssl requires from `sysconf` as its calling it to read some operating system limits.

**Comment by themodder666** [comment]
Stubbing them seems to work. How far along are you guys on the whole POSIX socket implementation?

**Comment by fwsGonzo** [comment]
working sockets, just no select/poll yet, and no async operation yet.. first up after im done implementing another networking driver is to make select work, and i think poll is probably "free" after select.
