### ISSUE TITLE
Need newlib GNU extensions

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#108]
While trying to port `mbw` (Memory bandwith test) I encountered this:
```
error: 'mempcpy' was not declared in this scope
```
[Newlib does implement `mempcpy`](https://sourceware.org/newlib/libc.html#mempcpy), but it's marked as a GNU extension -  `memcpy`, which is ANSI C works fine though.

We should find out how to get the GNU extensions into our newlib build.

**Comment by fwsGonzo** [comment]
We can use streamucpy here
