### ISSUE TITLE
Missing dependencies, python-jsonschema, python-psutil

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#1087]
The new `boot` tool requires python modules `jsonschema` and `psutil`, both available via `apt` on ubuntu and `brew` on mac.  Since we're promoting this as the recommended way to boot services we need to add these to the list of dependencies in `install.sh`

**Comment by alfred-bratterud** [comment]
I've fixed this for Linux (ubuntu/debian variants, arch and fedora, but only tested on ubuntu. @AndreasAakesson could you fix/test for macOS?

**Comment by AndreasAakesson** [comment]
Yes I'll take a look

**Comment by alfred-bratterud** [comment]
So this should now work on Linux and Mac, although we haven't tested on Arch or Fedora. Doing so is beyond our scope, so please let us know if you do.
