### ISSUE TITLE
256 color VGA example crashes

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#1123]
Some time after implementing CMake build system, the example broke. Not sure what caused it. I have ruled out the change to remove -mstackrealign, because it doesn't work after adding it back.

**Comment by SeanMooney** [comment]
this seems to be failing in int32.asm
so i dont think this was relateded to the cmake change.

in the serial output below you can see my "pre call assembly crap"
debug statement that was immediately before int32(0x10, &regs);
in vga_256_test() but not the "post call assembly crap" print ...

so ya looks like its happening in the real mode magic in the asm file


================================================================================
 IncludeOS v0.11.0-rc.2-388-g0669b5c (x86_64 / 64-bit)
 +--> Running [ 256 Color VGA Example Service ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
this is called before starting the test screen
                Enabled non-redirected IRQ 1 on LAPIC 0
                Enabled non-redirected IRQ 12 on LAPIC 0
pre call assembly crap

>>>> !!! CPU 0 EXCEPTION !!! <<<<
    Invalid Opcode (6)   EIP  0xa00ab1   CODE 0

  RAX:  0000000000c15de0  R 8:  0000000000c081c8
  RBX:  0000000000c15de0  R 9:  0000000000aaa490
  RCX:  0000000000c15de8  R10:  0000000000000001
  RDX:  0000000000000008  R11:  00000000000003ec

  RBP:  00000000009ffe60  R12:  0000000000000000
  RSP:  00000000009ffdb8  R13:  0000000000000000
  RSI:  00000000009ffde0  R14:  00000000009ffe0a
  RDI:  0000000000000010  R15:  000000002badb002
  RIP:  0000000000a00ab1  FLA:  0000000000000002

  CR0:  0000000080000033  CR4:  0000000000000620
  CR1:  0000000000000000  CR8:  0000000000000000
  CR2:  0000000000000000  GDT:  0000000000c07b40 (41)
  CR3:  0000000000001000  IDT:  0000000000c11d30 (2559)


        **** PANIC ****
* <VMRunner>:  VM signalled PANIC. Reading until EOT ( 0x4 )
CPU: 0, Reason: Invalid Opcode (6)
Heap is at: 0xc21000 / 0x1fdffff  (diff=20705279)
Heap usage: 42 / 20262 Kb
symtab or strtab is empty, indicating image may be stripped

[0] 0x0000000000a01aac + 0x000: 0xa01aac
[1] 0x0000000000a0e01c + 0x000: 0xa0e01c
[2] 0x0000000000a0e6e9 + 0x000: 0xa0e6e9
[3] 0x0000000000a00ab1 + 0x000: 0xa00ab1
[4] 0x0000000000a00a08 + 0x000: 0xa00a08
[5] 0x0000000000a067c1 + 0x000: 0xa067c1
[6] 0x0000000000a04fc5 + 0x000: 0xa04fc5
[7] 0x0000000000a124f5 + 0x000: 0xa124f5
[8] 0x0000000000a0e4c8 + 0x000: 0xa0e4c8

* <VMRunner>:  Stopping 256_color_vga_example PID 4820 with -SIGTERM
* <VMRunner>:   + child process  4821
* <VMRunner>:  Exit called with status 67 ( VM_PANIC )
* <VMRunner>:  Message: CPU: 0, Reason: Invalid Opcode (6)
Keep running:  False
* <VMRunner>:  Calling on_exit
* <VMRunner>:  Program exit called with status 67 ( VM_PANIC )
* <VMRunner>:  Stopping all vms

[ VM_PANIC ] CPU: 0, Reason: Invalid Opcode (6)

**Comment by SeanMooney** [comment]
i think this is being caused because the assembly is assuming we are runing in 32bit mode but now includeos is 64bit so we are running in long mode

if i compile with clang instead of gcc it show we are in long_mode

CPU: 0, Reason: Invalid Opcode (6)
Heap is at: 0xc77000 / 0x1ffdffff  (diff=523669503)
Heap usage: 43 / 511439 Kb

[0] 0x0000000000a01990 + 0x0fc: panic
[1] 0x0000000000a0df50 + 0x0ac: __cpu_exception
[2] 0x0000000000a0e6c9 + 0x000: __cpu_except_7
[3] 0x0000000000a00a90 + 0x001: _int32
[4] 0x0000000000a00960 + 0x088: Service::start(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
[5] 0x0000000000a06750 + 0x051: Service::start()
[6] 0x0000000000a04d30 + 0x275: OS::post_start()
[7] 0x0000000000a12470 + 0x065: kernel_start
[8] 0x0000000000a0e467 + 0x041: long_mode

**Comment by aldergames** [comment]
Any news on this topic? I would like to get this example working, but don't know enough about assembly to fix the issue. Can you post more exact instructions on how to build in 32 bit and run with qemu32?

I'm new to IncludeOS and qemu in general, so all I really know how to do is poke around the C++ code and build/run using the command:
`boot .`

**Comment by karra88** [comment]
TCP_perf is also showing this error `symtab or strtab is empty, indicating image may be stripped`

**Comment by fwsGonzo** [comment]
@aldergames @SeanMooney On dev it should be working now, as I wrote a custom VGA graphics module. I also added a starlight example where the graphics is animated.
