### ISSUE TITLE
Apple nasm (old) used on Mac OS Sierra

### ISSUE THREAD

**Issue by AnnikaH** [hioa-cs/IncludeOS#1155]
Error message when making IncludeOS on Mac Sierra:
apic_boot.asm:58: error: expression syntax error

nasm -v:
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Nov 15 2016
while nasm-2.12.02 is installed (via brew install nasm)

Temporary local bandaid:
In IncludeOS/src/CMakeLists.txt after include_directories:
set(CMAKE_ASM_NASM_COMPILER /usr/local/Cellar/nasm/2.12.02/bin/nasm)

**Comment by AndreasAakesson** [comment]
I think the solution is to let the install script for Mac symlink the brew nasm to the IncludeOS bin installation, and have the toolchain set the `CMAKE_ASM_NASM_COMPILER`.
