### ISSUE TITLE
DHCP times out on Google Compute Engine

### ISSUE THREAD

**Issue by fatlotus** [hioa-cs/IncludeOS#1270]
I'm following http://blog.includeos.org/2017/03/21/includeos-on-google-compute-engine, but I can't seem to get it working. Maybe a recent regression in the DHCP handling? I've tried builds on both `master` and `dev`.

(Everything works when run locally with qemu.)

Some logs: [verbose.log](https://github.com/hioa-cs/IncludeOS/files/877742/verbose.txt).

**Comment by fatlotus** [comment]
Here is a full, more [verbose.txt](https://github.com/hioa-cs/IncludeOS/files/877739/verbose.txt)

**Comment by fatlotus** [comment]
After applying the fix from #1246 (leaving the IP address set to `0.0.0.0` until we timeout), everything works. Problem solved :)

**Comment by ingve** [comment]
Thanks for trying IncludeOS on GCE and for the detailed log! As you found out, a fix was already in the queue, but we should have documented this better in the meantime. Please let us know if you run into any other issues!
