### ISSUE TITLE
"IP4 is still a thing" test case fails on macOS/OS X and Travis

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#1279]
The "IP4 is still a thing" test case in test/net/unit/ip4.cpp  passes on Jenkins, but fails on macOS Sierra, OS X El Capitan and on Travis:

> /Users/travis/build/ingve/IncludeOS/test/net/unit/ip4.cpp:201: failed: IP4 is still a thing: pass_count[Protocol::UDP] == passed + 1 for 0 == 1

@AnnikaH has found another test assertion in the same test case that also fails on macOS Sierra, but lest only prints the first failure in each test case.

**Comment by AnnikaH** [comment]
Yes, on my Mac, when an IP4 packet's src address is not set, the packet gets the IP src address of the packet created before. Like here, when setting the ip src address of ip_pckt_test, the ip src address of ip_pckt is set to the same, which affects if the packet gets dropped or not:
```
SECTION("Valid UDP packets gets passed on") {
      // Added by me to check if the next test gets this 10.10.5.5 IP: 
      auto ip_pckt_test = inet.create_ip_packet(Protocol::UDP);
      ip_pckt_test->set_ip_src({10,10,5,5});
      ip_pckt_test->make_flight_ready();
      EXPECT_PASS(std::move(ip_pckt_test), Protocol::UDP);

      // And the actual test that was in ip4.cpp (doesn't fail when the previous packet's IP is valid, which it is now):
      // Default initialized source and (0) gets through
      // (Might be for DHCPD)
      auto ip_pckt = inet.create_ip_packet(Protocol::UDP);
      printf("Packet IP: %s\n", ip_pckt->ip_src().to_string().c_str());    // This prints out IP 10.10.5.5
      ip_pckt->make_flight_ready();
      EXPECT_PASS(std::move(ip_pckt), Protocol::UDP);
}
```

**Comment by AndreasAakesson** [comment]
It's due to buffers being reused in bufferstore. No one takes the responsible on cleaning the memory, and no address is set anywhere for the source address.
