### ISSUE TITLE
vboxrun.sh and vmware script unable to run multiple instances of the same service

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#1284]
Both the `vboxrun.sh` script and the `vmware` script have incorrect assumptions about there only being one instance of each service, so if you try to start multiple instances of the same service, you get errors.

For the `vmware` script, a temporary workaround is to create multiple build folders and run one instance from each build folder.

**Comment by fwsGonzo** [comment]
Is this problem solved?
