### ISSUE TITLE
Acorn crash on demo_service - 0.10

### ISSUE THREAD

**Issue by perbu** [hioa-cs/IncludeOS#1295]
15bb0ab6 - (HEAD -> master, tag: v0.10.0, origin/master, origin/HEAD

Booting up the demo_service on OS X (Darwin 16.4.0) the vm crashes when I try to access the service: Service brought up with:

perbu::perbu { ~/git/IncludeOS/examples/demo_service }-> boot --create-bridge .

[ WARNING ] WARNING: Environment varialble INCLUDEOS_PREFIX is not set. Trying default /usr/local
* <boot>:  Creating bridge
>>> Creating network bridge for IncludeOS
>>> Using default settings
>>> Creating bridge bridge43, netmask 255.255.0.0, gateway 10.0.0.1
>>> Creating network bridge (requires sudo):
Password:
>>> Configuring network bridge (requires sudo):
* <VMRunner>:  Building with cmake ([])
> -- Looking for drivers in /usr/local/includeos/drivers
> -- 	* Found virtionet
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/perbu/git/IncludeOS/examples/demo_service/build
* <VMRunner>:  Building with 'make' (params=[])
> [100%] Built target service
> [100%] Built target pruned_elf_symbols
> [100%] Built target prepend_bootloader
egrep: /proc/cpuinfo: No such file or directory
[ WARNING ] Running with sudo
================================================================================

                           #include<os> // Literally

================================================================================
     [ Kernel ] Stack: 0x9fc94
     [ Kernel ] Boot args: 0x2badb002 (multiboot magic), 0x9500 (bootinfo addr)
     [ Kernel ] Max mem (from linker): 128 MiB
     [ Kernel ] Booted with multiboot
                * magic value: 0x2badb002 Multiboot info at 0x9500
                * Valid memory (130559 Kib):
                	 0x00000000 - 0x0009fbff (639 Kib)
                	 0x00100000 - 0x07fdffff (129920 Kib)

                * Booted with parameters @ 0x3000: IncludeOS_example
                * Multiboot provided memory map  (6 entries @ 0x9000)
                	 0x00000000 - 0x0009fbff FREE (639 Kb.)
                	 0x0009fc00 - 0x0009ffff RESERVED (1 Kb.)
                	 0x000f0000 - 0x000fffff RESERVED (64 Kb.)
                	 0x00100000 - 0x07fdffff FREE (129920 Kb.)
                	 0x07fe0000 - 0x07ffffff RESERVED (128 Kb.)
                	 0xfffc0000 - 0xffffffff RESERVED (256 Kb.)

     [ Kernel ] Assigning fixed memory ranges (Memory map)
     [ Kernel ] Assigning heap
     [ Kernel ] Printing memory map
                * Statman 4000 - 5fff (Statistics, 8192 / 8192 bytes used)
                * Kernel / service main stack a000 - 9fbff (N/A, 613376 / 613376 bytes used)
                * Reserved 9fc00 - 9ffff (Multiboot / BIOS, 1024 / 1024 bytes used)
                * Reserved f0000 - fffff (Multiboot / BIOS, 65536 / 65536 bytes used)
                * ELF 100000 - 2232e0 (Your service binary including OS, 1192673 / 1192673 bytes used)
                * Pre-heap 2232e1 - 22333f (Heap randomization area (not for use)), 95 / 95 bytes used)
                * Heap 223340 - 7fdffff (Dynamic memory, 7360 / 131845312 bytes used)
                * Reserved 7fe0000 - 7ffffff (Multiboot / BIOS, 131072 / 131072 bytes used)
                * Reserved fffc0000 - ffffffff (Multiboot / BIOS, 262144 / 262144 bytes used)
       [ INTR ] Creating exception handlers
                + Default interrupt gates set for irq >= 32
       [ ACPI ] Reading headers
                OEM: BOCHS  Rev. 0
       [ ACPI ] Reading APIC information
                LAPIC base: 0xfee00000  (flags: 0x1)
                -> CPU 0 ID 0  (flags=0x1)
                I/O APIC 0   ADDR 0xfec00000  INTR 0x0
                IRQ redirect for bus 0 from IRQ 0 to VEC 2
                IRQ redirect for bus 0 from IRQ 5 to VEC 5
                IRQ redirect for bus 0 from IRQ 9 to VEC 9
                IRQ redirect for bus 0 from IRQ 10 to VEC 10
                IRQ redirect for bus 0 from IRQ 11 to VEC 11
                LAPIC id: 0  ver: 50014

       [ APIC ] Enabling BSP LAPIC
                APIC_BASE MSR is now 0xfee00900

     [ IOAPIC ] Initializing
                Base addr: 0xfec00000  Redirection entries: 24
     [ IOAPIC ] Done
        [ BSP ] Enabling interrupts
                Enabled redirected IRQ 0 -> 2 on lapic 0
[ PCI Manager ] Probing PCI bus
                |
                +--+ Host Bridge (0x0)
                |
                +--+ ISA Bridge (0x1)
                |
                +--+ Mass Storage Controller
                |  +--+ Driver: Not found
                |
                +--+ Other Bridge (0x80)
                |
                +--+ Display Controller
                |
                +--+ Ethernet Network Controller (0x0)
                |  +--+ Driver: Found
     [ Virtio ] Attaching to  PCI addr 0x18
                [x] Vendor ID is VIRTIO
                [x] Device ID 0x1000 is in a valid range (Virtio LEGACY)
                [x] Device Revision ID (0x0) supported

                [ Resource @ BAR 0 ]
                  Address:  0xc000 Size: 0x20
                  Type: IO Resource

                [ Resource @ BAR 1 ]
                  Address:  0xfebd1000 Size: 0x1000
                  Type: Memory Resource

                [ Resource @ BAR 4 ]
                  Address:  0xfe000000 Size: 0x4000
                  Type: Memory Resource

                [x] Unit has valid I/O base (0xc000)
                [*] Reset device
                [x] Device has 3 MSI-X vectors
                MSI-X vector 0 pointing to cpu 0 intr 96
                MSI-X vector 1 pointing to cpu 0 intr 97
                MSI-X vector 2 pointing to cpu 0 intr 98
     [ Virtio ] Initialization complete
  [ VirtioNet ] Driver initializing
                [x] Negotiated needed features
                [x] Negotiated wanted features
                [ ] Device handles packets w. partial checksum
                [ ] Guest handles packets w. partial checksum
                [x] There's a control queue
                [x] Queue can handle any header/data layout
                [x] We can use indirect descriptors
                [x] There's a Ring Event Index to use
                [ ] There are multiple queue pairs
                [x] Merge RX buffers
                [x] RX queue assigned (0x52f000) to device
                [x] TX queue assigned (0x533000) to device
                [x] CTRL queue assigned (0x537000) to device
  [ VirtioNet ] Adding 128 receive buffers of size 1546
                [x] Valid Mac address: 52:54:00:12:34:56
                [x] Signalled driver OK
  [ VirtioNet ] Driver initialization complete
                [x] Link up

                |
                o
    [ Devices ] Listing registered devices
                |
                +--+ NIC
                |  + #0: eth0, driver VirtioNet
                |
                o
     [ Kernel ] Estimating CPU-frequency
                |
                +--(2 samples, 0.000100 sec. interval)
                |
                +--> 2339.009992 MHz
       [ APIC ] Measuring APIC timer...
                Enabled redirected IRQ 0 -> 2 on lapic 0
       [ CMOS ] RTC is 24 hour format, BCD mode
        [ RTC ] Enabling regular clock sync with CMOS
     [ Kernel ] Initializing plugins
     [ Kernel ] Starting IncludeOS minimal example
================================================================================
[ Super stack ] Constructing stacks
[ Super stack ] Creating stack for Nic eth0
      [ Inet4 ] Bringing up a IPv4 stack
      [ Inet4 ] Negotiating DHCP...
     [ DHCPv4 ] Negotiating IP-address (xid=870138099)
      [ Inet4 ] Network configured
                IP: 		10.0.0.42
                Netmask: 	255.255.255.0
                Gateway: 	10.0.0.1
                DNS Server: 	10.0.0.1
*** Basic demo service started ***
================================================================================
 IncludeOS v0.10.0
 +--> Running [ IncludeOS minimal example ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<Service> TCP STATUS:
LISTENERS:
Port	Queued
80	0

CONNECTIONS:
Proto	Recv	Send	In	Out	Local			Remote			State

     [ DHCPv4 ] Negotiation timed out
<Service> @on_connect: Connection 10.0.0.1:59527 successfully established.
<Service> @on_connect: Connection 10.0.0.1:59528 successfully established.
<Service> @on_read: 420 bytes received.
<Service> Request:
GET / HTTP/1.1
Host: 10.0.0.42
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Save-Data: on
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,nb;q=0.6,da;q=0.4,sv;q=0.2


<Service> Responding with 200 OK.
<Service> @on_write: 676 bytes written.
<Service> @on_read: 383 bytes received.
<Service> Request:
GET /favicon.ico HTTP/1.1
Host: 10.0.0.42
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Save-Data: on
Accept: image/webp,image/*,*/*;q=0.8
Referer: http://10.0.0.42/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,nb;q=0.6,da;q=0.4,sv;q=0.2


<Service> Responding with 404 Not Found.
<Service> @on_write: 69 bytes written.
^C
[ WARNING ] Process interrupted - stopping vms

[ ABORT ] Process terminated by user


--

Rebooting the VM makes it run fine.

**Comment by fwsGonzo** [comment]
Due to changes over time stabilizing 64-bit and other things, I'm just going to assume this is fixed (and if it's not a new issue is re-opened).
