### ISSUE TITLE
Some issues with mac installation

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#1432]
- Need proper check for the xcode installation. I installed xcode via the app store, but still had to run `xcode-select --install`.
- binutils installation failed when calling `install.sh`. To fix this the `etc/install_binutils.sh` script had to be called with sudo. (as it says in the comment in the `install.sh` script.) This needs to be investigated and fixed. (Is sudo actually needed?)
- Why do we have both `build_binutils.sh` and `install_binutils.sh`. Mac uses the install version, and the `create_binary_bundle.sh` uses build. Do we need both? (most likely)

**Comment by perbu** [comment]
I think this is resolved now @mnordsletten. Could you confirm?
