### ISSUE TITLE
Extend autoconf to allow DHCP configuration

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#1456]
mucho necessito

**Comment by AndreasAakesson** [comment]
It do support DHCP (see [configure test](https://github.com/hioa-cs/IncludeOS/blob/dev/test/net/integration/configure/config.json)), but it do not support "Try DHCP for 10 second, but set this static config if it fails".

**Comment by fwsGonzo** [comment]
https://github.com/hioa-cs/IncludeOS/pull/1457
