### ISSUE TITLE
DHCP timeout should be configurable 

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#1468]
The new more explicit network configuration system is awesome! 

In `configure.cpp`, the value "5.0" is hardcoded in two places:

```
if(method == "dhcp")
    {
      stack.negotiate_dhcp(5.0);
    }
```

and

```
else if(method == "dhcp-with-fallback")
    {
      // [...]
      stack.negotiate_dhcp(5.0, static_cfg);
  }
```

Sometimes 5 seconds is not enough (getting quite a few DHCP timeouts on VMware with bridged networking). Would it be better to make this timeout configurable, either in the `config.json` file or as a compile-time configurable `-DDHCP_TIMEOUT=...` setting?

**Comment by fwsGonzo** [comment]
Solved by https://github.com/hioa-cs/IncludeOS/pull/1476
