### ISSUE TITLE
vmxnet3 reads too small packet size in VMWare Fusion

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#1482]
Running a IncludeOS network service in VMWare Fusion (Mac OS) the maximum size that can be received seems to be *1510* when MTU is set to *1500*  (which means with Ethernet it should be *1514*). 
This only happens to me when using the vmxnet3 driver with VMWare, with qemu everything works fine.

How to replicate:
1. Add print to `vmxnet3::recv_packet`: `printf("<vmxnet3> RX Packet %d\n", size);`
2. Run a network service with `etc/wmware` script.
3. Ping the service with payload: 
`$ ping -s 1468 172.16.191.133`
`$ ping -s 1470 172.16.191.133`

Some output with different ping sizes (with IP debug) on WMVare:
```
<vmxnet3> RX Packet 1508
<IP4::receive> IP: tot_len=1494 cap=1480 dat=1474 PKT: sz=1494 cap=1500
<vmxnet3> RX Packet 1510
<IP4::receive> IP: tot_len=1496 cap=1480 dat=1476 PKT: sz=1496 cap=1500
<vmxnet3> RX Packet 1510
<IP4::receive> IP: tot_len=1498 cap=1480 dat=1476 PKT: sz=1496 cap=1500
<vmxnet3> RX Packet 1510
```
Qemu:
```
<vmxnet3> RX Packet 1510
<IP4::receive> IP: tot_len=1496 cap=1480 dat=1476 PKT: sz=1496 cap=1500
<vmxnet3> RX Packet 1512
<IP4::receive> IP: tot_len=1498 cap=1480 dat=1478 PKT: sz=1498 cap=1500
<vmxnet3> RX Packet 1514
<IP4::receive> IP: tot_len=1500 cap=1480 dat=1480 PKT: sz=1500 cap=1500
```

The only difference I've seen is qemu and vmware using different versions of the driver.
Qemu: `[ vmxnet3 ] Version 1.1` VMWare: `[ vmxnet3 ] Version 3.1`.

**Comment by fwsGonzo** [comment]
This problem happens on Workstation for Linux too and can be worked around by setting MTU to 1496

**Comment by YanVugenfirer** [comment]
Most probably the problem is here: https://github.com/hioa-cs/IncludeOS/blob/master/src/drivers/vmxnet3.cpp#L215

should be:
shared.misc.mtu = MTU();

**Comment by AndreasAakesson** [comment]
VMWare fusion on Mac shows the same issue again, now with TCP traffic. This time changing the MTU in the vmxnet3 constructor do not help either.
If the packet is a full segment (i.e MTU + 14 bytes (ethernet)), 4 bytes is missing of the reported length passed to the `recv_packet` function.

**Comment by fwsGonzo** [comment]
Same as https://github.com/hioa-cs/IncludeOS/issues/1519 (who would have thought!)

Solved by adding 4 bytes (size of VLAN tag) to buffer **without** changing MTU!

**Comment by fwsGonzo** [comment]
Solved with https://github.com/alfred-bratterud/IncludeOS/commit/c15756eb02143934b423019d08ca5d2b93a96cc8
