### ISSUE TITLE
vmxnet3 do not receive VLAN tagged packets in qemu

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#1519]
This is not the case when using VLAN in vmware fusion (using vmxnet3), nor when running in qemu using virtionet.

The first is confirmed by running the `examples/vlan` in vmware (with some black magic). 
The second is confirmed with `test/net/integration/vlan` (added in 
cb31f73). Changing the network device to be of type `vmxnet3` in `vm.json` will show the issue. I can see the VLAN tagged packets being transmitted and visible on the bridge in wireshark, but the packets do never arrive the other interface (checked by printing in `vmxnet3::recv_packet`).

**Comment by fwsGonzo** [comment]
Does vmxnet3 work now in workstation and fusion? @AndreasAakesson 

@mnordsletten what about on vcloud and ESXi? talking about packets with VLAN tag here

**Comment by AndreasAakesson** [comment]
It did before (when this issue was created). Not sure if the new changes to MTU has changed that.

**Comment by fwsGonzo** [comment]
Probably fixed now when removing the vlan-stripping feature bit.

**Comment by AndreasAakesson** [comment]
Most likely solved by #1945
