### ISSUE TITLE
Solo5/uvkm: automated test

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#1521]
Add an automated test for Solo5 integration. E.g. `./test/misc/integration/ukvm` that starts the demo service with ukvm and verifies ping / curl response.

**Comment by niks3089** [comment]
Is this already done? I wanted to pick this up but I see that test_ukvm.sh already tests demo_service unikernel

**Comment by ricarkol** [comment]
Yes @niks3089 this should be done.

@alfred-bratterud: are you OK with closing this?

**Comment by fwsGonzo** [comment]
It's being run as part of `misc` group on jenkins automatically, so I closed this
