### ISSUE TITLE
Building IncludeOS on Ubuntu 17.10

### ISSUE THREAD

**Issue by perbu** [hioa-cs/IncludeOS#1549]
@oleaamot mis-posted the following issue on the website tracker:

IncludeOS builds on Ubuntu 17.10 after applying the following patches and running "cd build_x86_64/ && make":

Remove references to __float128 in /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h
https://people.gnome.org/~ole/includeos/ubuntu-17.10-c++-20171029.patch

Configure "set(libliveupdate OFF)" and "option(libliveupdate "Build and install LiveUpdate" OFF)" in CMakeLists.txt
https://people.gnome.org/~ole/includeos/includeos-libliveupdate-off-20171029.patch

Enjoy,
Ole

**Comment by fwsGonzo** [comment]
```
$ lsb_release -a
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:printing-9.20160110ubuntu5-amd64:printing-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```
I'm running ubuntu 17.10 and using IncludeOS without issues.. is it building with g++ instead of clang?

**Comment by Enhex** [comment]
I'm getting problems with Ubuntu 17.10 too.
First of all compiling on 16.04.3 works.

On 17.10, solo5 fails to compile, and if it's disabled I'm getting similar error to the original post with `__float128` in `7.2.0/bits/std_abs.h`.

**Comment by oleaamot** [comment]
Here IncludeOS compiles on Ubuntu 17.10 from git after running

export CC="clang-6.0"
export CXX="clang++-6.0"

and after adding "#include <stdlib.h>" in these precompiled files:

/home/oka/IncludeOS/build_x86_64/precompiled/src/solo5_repo/ukvm/ukvm_hv_kvm.c:42:26: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’

/home/oka/IncludeOS/build_x86_64/precompiled/src/solo5_repo/ukvm/ukvm_hv_kvm_x86_64.c:46:17: note: include ‘<stdlib.h>’ or provide a declaration of ‘calloc’

/home/oka/IncludeOS/build_i686/precompiled/src/solo5_repo/ukvm/ukvm_hv_kvm.c:42:26: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’

/home/oka/IncludeOS/build_i686/precompiled/src/solo5_repo/ukvm/ukvm_hv_kvm_x86_64.c:46:17: note: include ‘<stdlib.h>’ or provide a declaration of ‘calloc’

IncludeOS minimal example runs after running ./test.sh

**Comment by ltearno** [comment]
As far as I understand, clang-3.8 is used by some dependencies of IncludeOs when build (like protobuf and solo5 for instance).
And clang-3.8 does not support __float_128 which is present in the ubuntu 17.10 stdlib header files.

My hack for the moment is to uninstall clang-3.8 and make two symbolic links so that includeos dependencies manage to be compiled with recent stdlib header :

        sudo ln -s /usr/bin/clang++-3.9 /usr/bin/clang++-3.8
        sudo ln -s /usr/bin/clang-3.9 /usr/bin/clang-3.8

This way I manage to have the entire IncludeOs to compile and 'boot' to work and the demo_service project to work.
