### ISSUE TITLE
Is it necessary to check if container is empty before running std::all_of?

### ISSUE THREAD

**Issue by mywtfmp3** [hioa-cs/IncludeOS#1565]
In `src/net/dhcp/dhcpd.cpp`
```c++
if (cid.empty() or std::all_of(cid.begin(), cid.end(), [] (int i) { return i == 0; }))
```

`std::all_of` returns `true` on empty containers. Is there any reason doing this?

I am learning C++ and people show me this repo to learn modern C++ programming. I am not sure this kind of question is appropriate here.

**Comment by RicoAntonioFelix** [comment]
You're correct, based on the information for [std::all_of](http://en.cppreference.com/w/cpp/algorithm/all_any_none_of) in the section `Return value`, the check for empty is superfluous...
