### ISSUE TITLE
clean the code on header.cpp file

### ISSUE THREAD

**Issue by mywtfmp3** [hioa-cs/IncludeOS#1590]
In [src/net/http/header.cpp](../blob/master/src/net/http/header.cpp) file, 
```c++
Header::Const_iterator Header::find(util::csview field) const noexcept {
  if (field.empty()) return fields_.cend();
  //-----------------------------------
  return
    std::find_if(fields_.cbegin(), fields_.cend(), [&field](const auto _) {
      return (_.first.length() == field.length())
        and std::equal(_.first.data(), _.first.data() + _.first.length(), field.data(), [](const auto a, const auto b) {
          return std::tolower(a) == std::tolower(b);
        });
    });
}
```

It's possible to get rid of  `_.fisrt.length == field.length` by using alternative `std::equal`.

`bool std::equal(InputIt1 first1, InputIt1 last1, InputIt2 first2, InputIt2 last2, BinaryPredicate p);`

And when comparing string and string_view, is it better to use `cbegin()`, `cend` consistently? Here is my code. 

```C++
Header::Const_iterator Header::find(util::csview field) const noexcept {
  if (field.empty()) return fields_.cend();
  //-----------------------------------
  return
    std::find_if(fields_.cbegin(), fields_.cend(), [&field](const auto _) {
      return std::equal(_.first.cbegin(), _.first.cend(), field.cbegin(), field.cend(), 
        [](const auto a, const auto b) { return std::tolower(a) == std::tolower(b); });
    });
}
```

**Comment by AndreasAakesson** [comment]
You're right. Have you confirmed that your solution works? We do have a [unit test](https://github.com/hioa-cs/IncludeOS/blob/dev/test/net/unit/http_header_test.cpp) for the Header class (extend it if needed).

Feel free to make PR's where you see improvements :)
