### ISSUE TITLE
diskbuilder fails due to opening too many files

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#1628]
When running diskbuilder from current dev with a memdisk directory containing just over 1000 files, diskbuilder fails after slightly over 200 files:

```
[ 20%] Generating memdisk.fat
diskbuilder: Could not open file default.expect.txt
diskbuilder: Could not open file default.txt
diskbuilder: Could not open file index.js
Unable to enter directory 0/java
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unable to enter directory 0/java
make[2]: *** [memdisk.fat] Abort trap: 6
```

The underlying error seems to be that diskbuilder fails because it has opened more files than it is allowed to. On macOS Sierra, the default limit for a process is 256 open files. If I call `setrlimit` with resource `RLIMIT_NOFILE` and set `rlim_cur` to a sufficiently large number, the diskbuilder process is allowed to run to completion, but this seems like a bit of a kludge. Does diskbuilder really need to keep all the files open at the same time?

**Comment by fwsGonzo** [comment]
May be due to unclosed directories. Does your tree have many directories? I'm committing a fix now, but I'm also going to try not adding subdirectories and files until I've closed the current level.

9ffa8f6875e70bb27fa299378528572fc7fd1056
