### ISSUE TITLE
Problem in running router example

### ISSUE THREAD

**Issue by karra88** [hioa-cs/IncludeOS#1686]
I am facing the below error when I am trying to run the router example

`Looking for chainloader: 
Found /usr/local/includeos/includeos/chainloader Type:  ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
[ WARNING ] Running with sudo
                * Initializing Autoconf plugin
   [ Autoconf ] Running auto configure
    [ Netconf ] Configuring network
    [ Netconf ] ! WARNING: Found more configs than there are interfaces
    [ Network ] Creating stack for VirtioNet on eth0
      [ Inet4 ] Bringing up eth0 on CPU 0
      [ Inet4 ] Network configured (52:54:00:12:34:56)
                IP: 		10.38.0.1
                Netmask: 	255.255.255.0
                Gateway: 	10.38.0.254
                DNS Server: 	10.38.0.254
     [ Kernel ] Exception thrown when initializing plugin: No IP4 stack found for [1] (missing driver?)

 IncludeOS v0.12.0-rc.2-dirty (x86_64 / 64-bit)
 +--> Running [ IncludeOS Router Service ]`
  [ Routeconf ] Reading route table #0...

	**** PANIC ****
CPU: 0, Reason: terminating with uncaught exception of type net::Stack_not_found: No IP4 stack found for [1] (missing driver?)
Heap is at: 0x4ca000 / 0x7fdffff  (diff=129064959)
Heap usage: 905 / 126945 Kb

[0] 0x0000000000113200 + 0x0fc: panic
[1] 0x000000000019b730 + 0x1ae: default_terminate_handler()
[2] 0x0000000000195c70 + 0x00e: std::__terminate(void (*)())
[3] 0x0000000000199200 + 0x02a: __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)
[4] 0x00000000001990e0 + 0x0af: __cxa_throw
[5] 0x000000000010f870 + 0x3ed: net::Inet<net::IP4>& net::Super_stack::get<net::IP4>(int)
[6] 0x00000000002132e0 + 0x31a: net::Route<net::IP4> net::parse_route<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&)
[7] 0x0000000000212340 + 0x26b: net::load_routing_table_from_cfg(int)
[8] 0x0000000000100170 + 0x04b: Service::start()
[9] 0x00000000001025f0 + 0x236: OS::post_start()
[10] 0x0000000000137a90 + 0x067: kernel_start
[11] 0x0000000000134eb3 + 0x041: long_mode
[ VM_PANIC ] CPU: 0, Reason: terminating with uncaught exception of type net::Stack_not_found: No IP4 stack found for [1] (missing driver?)`

In general, how to run the examples provided. Because for some files README is provided and for some it is not. 

Is there any document where some guidelines are provided for developing a new functionality ?

**Comment by AndreasAakesson** [comment]
Hi. Are you using master or dev branch? Both works fine for me here. How do you boot your services? Looks like you booted with only one network card. `net::Stack_not_found: No IP4 stack found for [1] (missing driver?)` (this is a bit misleading tho).
Are you using `boot .` to run the example? This will look into the `vm.json` and add 2 network cards.

(Btw, for a big code block, use triple _```_ at the start and end)

**Comment by karra88** [comment]
Thanks it worked. Why are we using name of the service binary to boot for tcp example ? 
What's the difference between `boot .` and `boot 'name of service binary'` ?

**Comment by AndreasAakesson** [comment]
`boot .` means it looks in the directory `.` if it is a CMake project, create dir `build/`, builds and boot the newly built binary in the `build/` directory.

`boot <path_to_service_binary>` will take any IncludeOS binary and boot it (in qemu).

Kinda 😄

**Comment by karra88** [comment]
Got it. 
@AndreasAakesson  Is there any document which provides an example on how to build a functionality from scratch?. 

I am going through "readthedocs". 

Just wanted to know if there are any other resources.

**Comment by AndreasAakesson** [comment]
What kind of functionality do you wanna make? A service? Or some OS functionality?

We don't have much more resources than readthedocs and our tests, examples and source code.

**Comment by karra88** [comment]
Planning to built a service. Thanks for the response.

**Comment by AndreasAakesson** [comment]
We got a [gitter channel](https://gitter.im/hioa-cs/IncludeOS) that you are more than welcome to join and ask questions (or just talk!). About Google Groups - not sure.

**Comment by karra88** [comment]
Great !!
