### ISSUE TITLE
Giving up early on DHCP

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#1716]
The OS now gives up on DHCP and never tries again even though it may just be a temporary problem. Secondly, the OS may be statically configured after a certain time passes. This is mostly because we run qemu with bridge, even though there are other network options that provide DHCP.

We need to explore:
- Retrying DHCP forever
- Rebooting after repeated failed contact on uplink, as no one wants a "bricked" instance
- Changing qemu bridged mode to use eg. NAT, host-local or other DHCP-enabled modes

**Comment by AndreasAakesson** [comment]
I suggest we make it so a timeout value of 0 seconds means "forever". It can then retry once every second (or less) for about 10 seconds, and after that fall back to something like once every 10th second.

**Comment by AndreasAakesson** [comment]
As stated in the PR, the option to try forever is now there. There is still a default timeout in Inet, which we could consider changing. Closing this issue for now.
