### ISSUE TITLE
Error with demo_linux

### ISSUE THREAD

**Issue by GaetanLongree** [hioa-cs/IncludeOS#1718]
On the dev branch, I followed the instruction to try and build the demo_linux image, but I'm encountering the following issues when executing make:

/usr/local/includeos/linux/liblinuxrt.a(os.cpp.o): In function `__arch_system_time()':
/home/gaetan/IncludeOS/linux/src/os.cpp:9: multiple definition of `__arch_system_time()'
/usr/local/includeos/linux/liblinuxrt.a(arch.cpp.o):/home/gaetan/IncludeOS/linux/src/arch.cpp:21: first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/service.dir/build.make:124: recipe for target 'linux_demo' failed
make[2]: *** [linux_demo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/service.dir/all' failed
make[1]: *** [CMakeFiles/service.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

OS: Ubuntu 16.04
GCC and G++ updated to 7.2
Executed the cmake and make commands in the ./linux folder without issues prior to attempting the demo_linux

One unrelated (I believe) issue I encountered when building ./linux, when using the default location (/usr/local/includeos) for the IncludeOS directory, specifying the INCLUDEOS_PREFIX variable in .bashrc and the DCMAKE_INSTALL_PREFIX cmake option causes the output of the make to be place in /usr/local/includeos/includeos. Removing the global variable and option solved the issue for ./linux.

**Comment by fwsGonzo** [comment]
You will have to make install the linux libraries again, as the changes I made for dev was specifically to fix these issues. Go into the /linux/build folder and `make -j4 install` to update the libraries and then run the linux demo again. Hope it works for you :)

**Comment by GaetanLongree** [comment]
Apologies, last time I check I was on the dev branch, it seemed I had reverted to the master branch by accident.

However, when trying to cmake on the dev branch, I keep getting these errors:
```
CMake Error at src/CMakeLists.txt:12 (add_library):
  CXX_STANDARD is set to invalid value '17'
CMake Error at userspace/CMakeLists.txt:93 (add_library):
  CXX_STANDARD is set to invalid value '17'
```

I tried searching the web but I cannot find the solution regarding this specific issue (despite having updated gcc and g++).

**Comment by fwsGonzo** [comment]
That's a bit harder to solve as it requires a newer CMake version to support... can you try editing the CMakeLists.txt and commenting out the set(CMAKE_CXX_STANDARD 17) line, then add -std=gnu++1z to the regular make options like this:
```
#set(CMAKE_CXX_STANDARD 17)
set(COMMON "-g -O2 -std=gnu++1z -march=native -Wall -Wextra")
```

**Comment by GaetanLongree** [comment]
Building ./linux works like a charm with the modifications to CMakeLists.txt you've given, however building the demo_linux outputs exactly the same error as before :/
(I deleted the entire build folder to start from scratch as a precaution)

**Comment by fwsGonzo** [comment]
Ah, maybe its the same problem there, and it needs the same treatment

**Comment by GaetanLongree** [comment]
Here are the steps I followed:
* Installed gcc-7 and g++-7, made sure they were used by default as gcc and g++
* Pulled latest commit from dev branch
* Edited the CMakeLists.txt in the ./linux folder as previously mentioned
* Made the build directory, ran cmake .. from ./linux/build/
* Ran `sudo make -j4 install` (had to run it in sudo because my includeos folder is in /usr/local)

I just re-verified and reran the cmake and make install to make sure, but I still get errors when trying to make the demo_linux (same errors as above) :/

**Comment by fwsGonzo** [comment]
@GaetanLongree did you ever figure this out? I can help you locate the issue tomorrow if you are still interested

**Comment by GaetanLongree** [comment]
Haven't given it much attention since I last checked.
I can try again with latest pull from dev branch, but I may end up not using this feature at all so we'll see.

**Comment by fwsGonzo** [comment]
I have recently updated the Linux platform to build and run even with GCC (although its not perfect), so I'm closing this for now. Feel free to re-open or create new issue if there is still build problems.
