### ISSUE TITLE
don't kprint panic EOT. 

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#1735]
As I understand it is right now only printed to serial port. We need this to sent as part of the transmission over uplink.

https://github.com/hioa-cs/IncludeOS/blob/master/src/kernel/syscalls.cpp#L227

**Comment by fwsGonzo** [comment]
Uplink uses websocket which has discrete messages with a specified length, so you don't actually need it :)

**Comment by mnordsletten** [comment]
Can we do this as well in the uplink? https://github.com/includeos/mothership/issues/366
The panic will then include the lines preceding the panic as well.
