### ISSUE TITLE
Implement Posix timer functionality

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#174]
We need `clock_gettime` to do #161, and newlib has that, but only if `_POSIX_TIMERS` is defined. We might need to rebuild newlib to enable this.

**Comment by alfred-bratterud** [comment]
We also need `clock_gettime` for lest (and that's all it needs). I did a stub [here](https://github.com/hioa-cs/IncludeOS/blob/e3f91a8d6a8f381a3ab1b586581676b0de9171d7/test/STL/service.cpp#L35)

**Comment by alfred-bratterud** [comment]
We have CMOS-time now, with a helper to compute seconds since epoch. The issue with using that directly is that it's horribly expensive, like 200k cycles (!) depending on your system (lots of vm exits). We're looking at how we can implement better time-keeping solution, without relying on regular timer interrupts (which we only have on if timers are active).

**Comment by fwsGonzo** [comment]
Implemented with RTC.
