### ISSUE TITLE
install IncludeOS on openSUSE Leap 42.3

### ISSUE THREAD

**Issue by jbarraca** [hioa-cs/IncludeOS#1740]
is there a way to install IncludeOS on this OS ?

I tried to use the script install_from_bundle.sh but i get this error 

`/usr/bin/clang
/usr/bin/clang++

>>> Best guess for compatible compilers: clang++ / clang

>>> Building IncludeOS
~/IncludeOS/build_aarch64 ~/IncludeOS
-- Target CPU aarch64
-- Target triple aarch64-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- Init git submodule: mod/GSL
-- Init git submodule: mod/http-parser
-- Init git submodule: mod/uzlib
-- Init git submodule: mod/rapidjson
-- Init git submodule: NaCl
CMake Error at src/CMakeLists.txt:76 (add_subdirectory):
  add_subdirectory given source "arch/aarch64" which is not an existing
  directory.

-- Init git submodule: lib/protobuf
-- Configuring incomplete, errors occurred!
See also "/root/IncludeOS/build_aarch64/CMakeFiles/CMakeOutput.log".
See also "/root/IncludeOS/build_aarch64/CMakeFiles/CMakeError.log".
`

**Comment by fwsGonzo** [comment]
Perhaps you have an environment variable called ARCH set to aarch64? You can try `unset ARCH` and see what happens.

**Comment by jbarraca** [comment]
well i changed the file to use ARCH = aarch64 in the beginning of the script install_from_bundle.sh  because that is my cpu architecture:
![image](https://user-images.githubusercontent.com/33351821/38617039-dd313c0a-3d8d-11e8-843a-f703a5b5e49b.png)

It cant be installed with this architecture?

**Comment by jbarraca** [comment]
i tried to do everything again and now i got this error:
![image](https://user-images.githubusercontent.com/33351821/38618099-8f7be642-3d90-11e8-90bf-a0740506319f.png)

**Comment by fwsGonzo** [comment]
Unfortunately, we only support i686 and x86_64 (amd64) as arches. We have prebuilt bundles for many dependencies, such as the C/C++ standard libraries. Building all the bundles correctly and verifying everything for a new arch is a big task.

**Comment by jbarraca** [comment]
My OS is running directly on a Raspberry Pi 3. My goal was to deploy IncludeOS unikernels on top of the ukvm (solo5) which was already installed. 
Thank you for the support anyway
