### ISSUE TITLE
error testing the installation! (ubuntu 14.04 x86_64)

### ISSUE THREAD

**Issue by jbarraca** [hioa-cs/IncludeOS#1742]
when i run the demo_service example this happens:

![image](https://user-images.githubusercontent.com/33351821/38709301-2ffc43e2-3eb2-11e8-8a26-516959f9d30f.png)

does anyone know how to fix this ?

**Comment by fwsGonzo** [comment]
I haven't seen that error before, but assuming you are only booting 64-bit binaries you can go into vmrunner/vmrunner.py line 428 and just comment out everything such that we assume ELF is 64-bit:

```
            #info ("File magic: ", file_type(image_name))

            #if is_Elf64(image_name):
                info ("Found 64-bit ELF, need chainloader" )
                print "Looking for chainloader: "
                print "Found", chainloader, "Type: ",  file_type(chainloader)
                if not is_Elf32(chainloader):
                    print color.WARNING("Chainloader doesn't seem to be a 32-bit ELF executable")
                kernel_args = ["-kernel", chainloader, "-append", kernel_args, "-initrd", image_name + " " + kernel_args]
            #elif is_Elf32(image_name):
            #    info ("Found 32-bit elf, trying direct boot")
            #    kernel_args = ["-kernel", image_name, "-append", kernel_args]
            #else:
            #    print color.WARNING("Provided kernel is neither 64-bit or 32-bit ELF executable.")
            #    kernel_args = ["-kernel", image_name, "-append", kernel_args]
```

**Comment by jbarraca** [comment]
i was getting some strange errors on ubuntu 14.04 so i ended up installing ubuntu 17.10. bue when i run the demo serverice the CPU panics : 
![image](https://user-images.githubusercontent.com/33351821/38739286-5f48d6c2-3f2c-11e8-9f2a-f756fe3b1734.png)

can you help ?

**Comment by jbarraca** [comment]
no i didnt change anything . i just cloned the folder and typed ./install.sh.
i removed the /IncludeOS/examples/demo_service/build and runned boot --create-bridge .
this was the result:

apu1@apu1:~/IncludeOS/examples/demo_service$ boot --create-bridge .
[ WARNING ] WARNING: Environment variable INCLUDEOS_PREFIX is not set. Trying default /usr/local
* <boot>:  Creating bridge
    Creating network bridge for IncludeOS 
    Using default settings 
    Creating bridge bridge43, netmask 255.255.255.0, gateway 10.0.0.1 
    Network bridge already created
    Network bridge already configured
    Network bridge already activated
* <VMRunner>:  Building with cmake ([])
> -- Building for arch x86_64, platform x86_pc
> -- The C compiler identification is GNU 7.2.0
> -- The CXX compiler identification is GNU 7.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Target triple x86_64-pc-linux-elf
> -- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
> -- The ASM_NASM compiler identification is NASM
> -- Found assembler: /usr/bin/nasm
> -- Building without threading / SMP
> -- Looking for drivers in /usr/local/includeos/x86_64/drivers
> -- 	* Found virtionet
> -- 	* Found vmxnet3
> -- 	* Found boot_logger
> -- 	* Found default_stdout
> -- Looking for plugins in /usr/local/includeos/x86_64/plugins
> -- 	* Found autoconf
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/apu1/IncludeOS/examples/demo_service/build
* <VMRunner>:  Building with 'make' (params=[])
In file included from /usr/local/includeos/x86_64/include/libcxx/cmath:305:0,
                 from /home/apu1/IncludeOS/examples/demo_service/service.cpp:18:
/usr/local/includeos/api/posix/math.h:67:13: warning: declaration of 'long double ldexpl(long double, long double)' conflicts with built-in declaration 'long double ldexpl(long double, int)' [-Wbuiltin-declaration-mismatch]
 long double ldexpl(long double, long double);
             ^~~~~~
/usr/local/includeos/api/posix/math.h:69:13: warning: declaration of 'long double ilogbl(long double)' conflicts with built-in declaration 'int ilogbl(long double)' [-Wbuiltin-declaration-mismatch]
 long double ilogbl(long double);
             ^~~~~~
/usr/local/includeos/api/posix/math.h:71:13: warning: declaration of 'long double llroundl(long double)' conflicts with built-in declaration 'long long int llroundl(long double)' [-Wbuiltin-declaration-mismatch]
 long double llroundl(long double);
             ^~~~~~~~
/usr/local/includeos/api/posix/math.h:75:13: warning: declaration of 'long double lroundl(long double)' conflicts with built-in declaration 'long int lroundl(long double)' [-Wbuiltin-declaration-mismatch]
 long double lroundl(long double);
             ^~~~~~~
/usr/local/includeos/api/posix/math.h:80:13: warning: declaration of 'long double nexttowardf(long double, long double)' conflicts with built-in declaration 'float nexttowardf(float, long double)' [-Wbuiltin-declaration-mismatch]
 long double nexttowardf(long double, long double);
             ^~~~~~~~~~~
/usr/local/includeos/api/posix/math.h:85:13: warning: declaration of 'long double scalblnl(long double, long double)' conflicts with built-in declaration 'long double scalblnl(long double, long int)' [-Wbuiltin-declaration-mismatch]
 long double scalblnl(long double, long double);
             ^~~~~~~~
/usr/local/includeos/api/posix/math.h:86:13: warning: declaration of 'long double scalbnl(long double, long double)' conflicts with built-in declaration 'long double scalbnl(long double, int)' [-Wbuiltin-declaration-mismatch]
 long double scalbnl(long double, long double);
             ^~~~~~~
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 8f035202  ELF strings: c9432381  ELF section: e9089665
/usr/bin/objcopy: sthEvhPY: section .bss lma 0x4b5000 adjusted to 0x53f1cd
/usr/bin/strip: stsXDeo4: section .bss lma 0x4b5000 adjusted to 0x53f1cd
> [ 20%] Generating config_json.o
> Scanning dependencies of target config_json
> [ 40%] Linking CXX static library libconfig_json.a
> [ 40%] Built target config_json
> Scanning dependencies of target service
> [ 80%] Building CXX object CMakeFiles/service.dir/service.cpp.o
> [ 80%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
> [100%] Linking CXX executable IncludeOS_example
> [100%] Built target service
> Scanning dependencies of target pruned_elf_symbols
> Scanning dependencies of target prepend_bootloader
> [100%] Built target prepend_bootloader
> [100%] Built target pruned_elf_symbols
Looking for chainloader: 
Found /usr/local/includeos/chainloader Type:  ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
[ WARNING ] Running with sudo

>>>> !!! CPU 0 EXCEPTION !!! <<<<
Divide-by-zero Error (0)   EIP  0xed890   CODE 0

  EAX:  739937a4  EBP:  0029d141
  EBX:  0029d141  ESP:  bc2badb0
  ECX:  2badb031  ESI:  2badb002
  EDX:  2b846142  EDI:  0029d141

  EIP:  000ed890  EFL:  00000082


	**** PANIC ****
CPU: 0, Reason: Divide-by-zero Error (0)
Heap is at: 0x6bb000 / 0xffffffff  (diff=4287909887)
Heap usage: 4 / 4187416 Kb

[0] 0x00102cc0 + 0x102: panic
[1] 0x0010a270 + 0x0d6: __cpu_exception
[2] 0x0010a429 + 0x000: __cpu_except_1
[3] 0x000ed890 + 0x000: 0xed890
^A^Z
[4]+  Stopped                 boot --create-bridge .

**Comment by fwsGonzo** [comment]
Ah, its because the C/C++ compiler is the GNU compiler. We don't support that on our dev branch, but we have an upcoming branch where its very likely supported. If you install `clang-5.0` or later version it will work! :) :+1:

**Comment by jbarraca** [comment]
i get the same error : 

apu2@apu2:~/IncludeOS$ export CC=clang-5.0
apu2@apu2:~/IncludeOS$ export CXX=clang++-5.0
apu2@apu2:~/IncludeOS$ ./test.sh 
~/IncludeOS/examples/demo_service ~/IncludeOS
~/IncludeOS/examples/demo_service/build ~/IncludeOS/examples/demo_service ~/IncludeOS
-- Building for arch x86_64, platform x86_pc
-- The C compiler identification is Clang 5.0.2
-- The CXX compiler identification is Clang 5.0.2
-- Check for working C compiler: /usr/bin/clang-5.0
-- Check for working C compiler: /usr/bin/clang-5.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-5.0
-- Check for working CXX compiler: /usr/bin/clang++-5.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target triple x86_64-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Building without threading / SMP
-- Looking for drivers in /usr/local/includeos/x86_64/drivers
-- 	* Found virtionet
-- 	* Found vmxnet3
-- 	* Found boot_logger
-- 	* Found default_stdout
-- Looking for plugins in /usr/local/includeos/x86_64/plugins
-- 	* Found autoconf
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apu2/IncludeOS/examples/demo_service/build
[ 20%] Generating config_json.o
Scanning dependencies of target config_json
[ 40%] Linking CXX static library libconfig_json.a
[ 40%] Built target config_json
Scanning dependencies of target service
[ 60%] Building CXX object CMakeFiles/service.dir/service.cpp.o
[ 80%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
[100%] Linking CXX executable IncludeOS_example
[100%] Built target service
Scanning dependencies of target prepend_bootloader
[100%] Built target prepend_bootloader
Scanning dependencies of target pruned_elf_symbols
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 8e017dd8  ELF strings: 1b629318  ELF section: bd08d020
/usr/bin/objcopy: stFIoJ73: section .bss lma 0x4aa000 adjusted to 0x52c2e1
/usr/bin/strip: stunjQS9: section .bss lma 0x4aa000 adjusted to 0x52c2e1
[100%] Built target pruned_elf_symbols
Build complete 

Starting VM with Qemu. 
(Once inside Qemu, 'Ctrl+a c' will enter the Qemu console, from which you can type 'q' to quit.)

You should now get a boot message from the virtual machine:
[ WARNING ] WARNING: Environment variable INCLUDEOS_PREFIX is not set. Trying default /usr/local
Looking for chainloader: 
Found /usr/local/includeos/chainloader Type:  ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
[ WARNING ] Running with sudo

>>>> !!! CPU 0 EXCEPTION !!! <<<<
Divide-by-zero Error (0)   EIP  0xed890   CODE 0

  EAX:  0029d141  EBP:  0029d141
  EBX:  0029d141  ESP:  d2bc2bad
  ECX:  2badb031  ESI:  2badb002
  EDX:  2badb002  EDI:  0029d141

  EIP:  000ed890  EFL:  00000886


	**** PANIC ****
CPU: 0, Reason: Divide-by-zero Error (0)
Heap is at: 0x6a8000 / 0xffffffff  (diff=4287987711)
Heap usage: 4 / 4187492 Kb

[0] 0x00102cc0 + 0x102: panic
[1] 0x0010a270 + 0x0d6: __cpu_exception
[2] 0x0010a429 + 0x000: __cpu_except_1
[3] 0x000ed890 + 0x000: 0xed890

**Comment by fwsGonzo** [comment]
It's probably because something, for example the chainloader, is still using GCC as compiler. Try removing the src/chainload/build folder and see if that helps!

**Comment by jbarraca** [comment]
well now that you mention that, every time i run the script i need to do:
    export CC=clang-5.0
    export CXX=clang++5.0
or else another compiler is used (cc or c++)

and i've got way back on the terminal and noticed that at the end of the installation i got this:
    -- Installing: /usr/local/includeos/i686/lib/libliveupdate.a
-- Installing: /usr/local/includeos/i686/lib/libmicrolb.a
~/IncludeOS


>>> Done! IncludeOS bundle downloaded and installed


>>> Building chainloader
~/IncludeOS/src/chainload/build ~/IncludeOS
-- Building for arch i686, platform x86_nano
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake root: /usr/local
-- Target triple i686-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Building without threading / SMP
-- Looking for drivers in /usr/local/includeos/i686/drivers
-- 	* Found default_stdout
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apu2/IncludeOS/src/chainload/build
Scanning dependencies of target service
[ 75%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/service.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/hotswap.cpp.o
[100%] Linking CXX executable chainloader
[100%] Built target service
Scanning dependencies of target prepend_bootloader
Scanning dependencies of target pruned_elf_symbols
[ vmbuild ] Warning: found 2 loadable segments. Loading as one.
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 34cccfe6  ELF strings: 7a4f83fa  ELF section: b1de3631
/usr/bin/objcopy: stsncEQs: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target prepend_bootloader
/usr/bin/strip: stTCKeop: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target pruned_elf_symbols
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/includeos/chainloader
~/IncludeOS


>>> IncludeOS installation Done!
    To use IncludeOS set env variables for cmake to know your compiler, e.g.:
        export CC="clang-5.0"
        export CXX="clang++-5.0"
    
    Test your installation with ./test.sh


maybe the problem is here. if it is, what can i do to make clang5 as the default compiler ?

**Comment by jbarraca** [comment]
i did that and re-installed. in the beginning of the installation the compiler was clang, but at the end the compiler is the gnu compiler again... and even the arch is wrong, instead of the x86_64 it is i686.

>>> Building chainloader
~/IncludeOS/src/chainload/build ~/IncludeOS
-- Building for arch i686, platform x86_nano
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake root: /usr/local
-- Target triple i686-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Building without threading / SMP
-- Looking for drivers in /usr/local/includeos/i686/drivers
-- 	* Found default_stdout
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apu2/IncludeOS/src/chainload/build
Scanning dependencies of target service
[ 75%] Building CXX object CMakeFiles/service.dir/hotswap.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/service.cpp.o
[100%] Linking CXX executable chainloader
[100%] Built target service
Scanning dependencies of target prepend_bootloader
Scanning dependencies of target pruned_elf_symbols
[ vmbuild ] Warning: found 2 loadable segments. Loading as one.
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 34cccfe6  ELF strings: 7a4f83fa  ELF section: b1de3631
/usr/bin/objcopy: st3zL0U3: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target prepend_bootloader
/usr/bin/strip: stzutAKb: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target pruned_elf_symbols
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/includeos/chainloader
~/IncludeOS


>>> IncludeOS installation Done!
    To use IncludeOS set env variables for cmake to know your compiler, e.g.:
        export CC="clang-5.0"
        export CXX="clang++-5.0"
    
    Test your installation with ./test.sh
apu2@apu2:~/IncludeOS$ ./test.sh
~/IncludeOS/examples/demo_service ~/IncludeOS
~/IncludeOS/examples/demo_service/build ~/IncludeOS/examples/demo_service ~/IncludeOS
-- Building for arch x86_64, platform x86_pc
-- The C compiler identification is Clang 5.0.2
-- The CXX compiler identification is Clang 5.0.2
-- Check for working C compiler: /usr/bin/clang-5.0
-- Check for working C compiler: /usr/bin/clang-5.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-5.0
-- Check for working CXX compiler: /usr/bin/clang++-5.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target triple x86_64-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Building without threading / SMP
-- Looking for drivers in /usr/local/includeos/x86_64/drivers
-- 	* Found virtionet
-- 	* Found vmxnet3
-- 	* Found boot_logger
-- 	* Found default_stdout
-- Looking for plugins in /usr/local/includeos/x86_64/plugins
-- 	* Found autoconf
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apu2/IncludeOS/examples/demo_service/build
[ 20%] Generating config_json.o
Scanning dependencies of target config_json
[ 40%] Linking CXX static library libconfig_json.a
[ 40%] Built target config_json
Scanning dependencies of target service
[ 60%] Building CXX object CMakeFiles/service.dir/service.cpp.o
[ 80%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
[100%] Linking CXX executable IncludeOS_example
[100%] Built target service
Scanning dependencies of target prepend_bootloader
[100%] Built target prepend_bootloader
Scanning dependencies of target pruned_elf_symbols
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 8e017dd8  ELF strings: 1b629318  ELF section: bd08d020
/usr/bin/objcopy: stjpmE5f: section .bss lma 0x4aa000 adjusted to 0x52c2e1
/usr/bin/strip: stEvlmUk: section .bss lma 0x4aa000 adjusted to 0x52c2e1
[100%] Built target pruned_elf_symbols
Build complete 

Starting VM with Qemu. 
(Once inside Qemu, 'Ctrl+a c' will enter the Qemu console, from which you can type 'q' to quit.)

You should now get a boot message from the virtual machine:
[ WARNING ] WARNING: Environment variable INCLUDEOS_PREFIX is not set. Trying default /usr/local
Looking for chainloader: 
Found /usr/local/includeos/chainloader Type:  ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped
[ WARNING ] Running with sudo
[sudo] password for apu2: 

>>>> !!! CPU 0 EXCEPTION !!! <<<<
Divide-by-zero Error (0)   EIP  0xed890   CODE 0

  EAX:  0029d25c  EBP:  0029d141
  EBX:  0029d141  ESP:  bc2badb0
  ECX:  2badb031  ESI:  2badb002
  EDX:  2badb002  EDI:  0029d141

  EIP:  000ed890  EFL:  00000013


	**** PANIC ****
CPU: 0, Reason: Divide-by-zero Error (0)
Heap is at: 0x6a8000 / 0xffffffff  (diff=4287987711)
Heap usage: 4 / 4187492 Kb

[0] 0x00102cc0 + 0x102: panic
[1] 0x0010a270 + 0x0d6: __cpu_exception
[2] 0x0010a429 + 0x000: __cpu_except_1
[3] 0x000ed890 + 0x000: 0xed890
^A^Z
[1]+  Stopped                 ./test.sh

**Comment by fwsGonzo** [comment]
ok try this
```
rm -rf src/chainload/build
mkdir -p src/chainload/build
pushd src/chainload/build
cmake .. -DCMAKE_INSTALL_PREFIX=$INCLUDEOS_PREFIX
make -j install
popd
```

**Comment by jbarraca** [comment]
when i run the cmake .. -DCMAKE_INSTALL_PREFIX=$INCLUDEOS_PREFIX
it is supposed to compile with gnu ?

root@apu2:/home/apu2/IncludeOS# rm -rf src/chainload/build
root@apu2:/home/apu2/IncludeOS# mkdir -p src/chainload/build
root@apu2:/home/apu2/IncludeOS# pushd src/chainload/build
/home/apu2/IncludeOS/src/chainload/build /home/apu2/IncludeOS
root@apu2:/home/apu2/IncludeOS/src/chainload/build# cmake .. -DCMAKE_INSTALL_PREFIX=$INCLUDEOS_PREFIX
-- Building for arch i686, platform x86_nano
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake root: /usr/local
-- Target triple i686-pc-linux-elf
-- Using vanilla CPU features: SSE3. CAPABS = -msse3 -mfpmath=sse
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Building without threading / SMP
-- Looking for drivers in /usr/local/includeos/i686/drivers
-- 	* Found default_stdout
-- Configuring done
-- Generating done
-- Build files have been written to: /home/apu2/IncludeOS/src/chainload/build
root@apu2:/home/apu2/IncludeOS/src/chainload/build# make -j install
Scanning dependencies of target service
[ 75%] Building CXX object CMakeFiles/service.dir/service.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/hotswap.cpp.o
[ 75%] Building CXX object CMakeFiles/service.dir/usr/local/includeos/src/service_name.cpp.o
[100%] Linking CXX executable chainloader
[100%] Built target service
Scanning dependencies of target prepend_bootloader
Scanning dependencies of target pruned_elf_symbols
[ vmbuild ] Warning: found 2 loadable segments. Loading as one.
/usr/local/includeos/bin/elf_syms: Pruning ELF symbols 
ELF symbols: 34cccfe6  ELF strings: 7a4f83fa  ELF section: b1de3631
/usr/bin/objcopy: stp9US0J: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target prepend_bootloader
/usr/bin/strip: stF6wjWK: section .bss lma 0x2e4d80 adjusted to 0x32dfbf
[100%] Built target pruned_elf_symbols
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/includeos/chainloader
root@apu2:/home/apu2/IncludeOS/src/chainload/build# popd

**Comment by jbarraca** [comment]
it is also building for the wrong arch

**Comment by fwsGonzo** [comment]
No its not supposed to build with GNU, but it is supposed to be 32-bit.

```
export CC=clang-5.0
export CXX=clang++-5.0
rm -rf src/chainload/build
mkdir -p src/chainload/build
pushd src/chainload/build
cmake .. -DCMAKE_INSTALL_PREFIX=$INCLUDEOS_PREFIX
make -j install
popd
```

**Comment by jbarraca** [comment]
it worked! i think the problem was that in the root user, CC/CXX variables were not defined :)

*** Basic demo service started ***
<Service> TCP STATUS:
LISTENERS:
Local	Queued
0.0.0.0:80	0

CONNECTIONS:
Proto	Recv	Send	In	Out	Local			Remote		State

     [ DHCPv4 ] Negotiation timed out (eth0)
    [ Netconf ] DHCP timeout (eth0) - falling back to static configuration
      [ Inet4 ] Network configured (52:54:00:12:34:56)
                IP: 		10.0.0.42
                Netmask: 	255.255.255.0
                Gateway: 	10.0.0.1
                DNS Server: 	10.0.0.1
