### ISSUE TITLE
error running my first service

### ISSUE THREAD

**Issue by jbarraca** [hioa-cs/IncludeOS#1746]
$ cp -r seed/service ~/my_service
    $ cd ~/my_service
    $ emacs service.cpp
    ... add your code  **(i didn't change anything from the example)**
    $ mkdir build && cd build
    $ cmake ..
    $ make
    $ boot my_service

when i run the the above tutorial i get an qemu error:

$ boot my_service
[ WARNING ] WARNING: Environment variable INCLUDEOS_PREFIX is not set. Trying default /usr/local
[ WARNING ] Provided kernel is neither 64-bit or 32-bit ELF executable.
[ WARNING ] Running with sudo
[ WARNING ] Stderr: 
warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu: could not load kernel 'my_service': No such file or directory

**Comment by fwsGonzo** [comment]
The `seed` service is actually called `seed`. Guess that's a mistake in the documentation. You can also go one folder down and just do `boot .` to run any service without knowing its binary name.

**Comment by jbarraca** [comment]
it worked both with `boot .` one folder down and with `boot seed` in the build folder! 
Thanks for the insight!
