### ISSUE TITLE
Website is not displayed when using `test_ukvm.sh`

### ISSUE THREAD

**Issue by mhk** [hioa-cs/IncludeOS#1764]
## Problem:
TCP-Connection is opened but no replies are received on the client side.

## Expected:
Server response is shown.

## Steps to reproduce:

1. Install ubuntu 16.04
2. Execute following steps in terminal:
    ```
    export INCLUDEOS_PREFIX=~/includeos/
    export PATH=$PATH:$INCLUDEOS_PREFIX/bin
    git clone https://github.com/hioa-cs/IncludeOS
    cd IncludeOS
    ./install.sh
    ./test_ukvm.sh
    ```
3. Open second terminal and execute `telnet 10.0.0.42 80` and enter following text:
    ```
    GET /index.html
    ```
    The connection stays open, but no reply is received.

### Expected
Output of the `telnet` client:
```
GET /index.html
HTTP/1.1 404 Not Found
Server: IncludeOS/0.10
Connection: close
```

Server log:
```
<Service> @on_read: 17 bytes received.
<Service> Request:
GET /index.html HTTP/1.1

<Service> Responding with 404 Not Found.
<Service> @on_write: 69 bytes written.
```

### Actual
The telnet client hangs (no reply from server is shown):
```
GET /index.html


```

Server log:
```
<Service> @on_read: 17 bytes received.
<Service> Request:
GET /index.html HTTP/1.1

<Service> Responding with 404 Not Found.
<Service> @on_write: 69 bytes written.
```

**Comment by ingve** [comment]
Thanks for trying IncludeOS!

Are you using the master or the dev branch?

Have you verified that the example service works properly using QEMU or another hypervisor? (your expected output above would seem to suggest yes; just checking) :)

**Comment by mhk** [comment]
It works fine with `qemu` and `kvm` and I verified, that the bridge (`bridge42`) and tap (`tap100`) are created.
As stated the server receives the client data, but something goes wrong when the server sends the response.

**Comment by niks3089** [comment]
This is probably because of #1751. Can you try on dev branch?

**Comment by mhk** [comment]
Current `dev` branch works for me now. 
FYI: I found another bug in the `dev` branch #1781
