### ISSUE TITLE
Stopping a uniekrnel

### ISSUE THREAD

**Issue by Kuvesz** [hioa-cs/IncludeOS#1816]
Hey there!

I'm trying to stop a test as soon as it finishes, and so far no luck. I return from the Service::start function after all is done, but that seems to do nothing. (Yes I can quit with Ctrl+C, but I want it to happen automatically.)

Thanks for the help in advance.

**Comment by fwsGonzo** [comment]
`OS::shutdown()` or to shutdown immediately
```
#include <arch.hpp>
__arch_poweroff();
```

**Comment by Kuvesz** [comment]
Oh, thank you very much. (Sorry, kind of a C++ noob here.)

**Comment by AndreasAakesson** [comment]
Good of you to ask then! :) `Service::start` is the entry point for "userspace code". When the function returns the OS continues to handle the event loop. If no events it will just sleep and wait for an interrupt.

We do actually also got the classic `int main(..)` signature, which will do as you expect it to do (exit on return). [Here's an example](https://github.com/hioa-cs/IncludeOS/blob/master/test/posix/integration/main/service.cpp#L22)

**Comment by Kuvesz** [comment]
Oh I see. I actually went through your code for something else, but mainly the python part, so I didn't have much of an idea what was going on, I just though that if I return the unikernel will eventualy run it's coure and quit, but thank you guys for helping. :)
