### ISSUE TITLE
Moving a delegate does not make it "empty"

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#1821]
```
delegate<void()> del;
// fine
assert(not del);
assert(del == nullptr);

del = [](){};
// fine
assert(del);
assert(del != nullptr);

auto del2 = std::move(del);
// fine
assert(del2);
assert(del2 != nullptr);
// not fine
assert(not del);
assert(del == nullptr);
```

```
class delegate {
...
	bool operator== (std::nullptr_t) const noexcept
	{
		return storage_.empty();
	}

	bool operator!= (std::nullptr_t) const noexcept
	{
		return !storage_.empty();
	}

	explicit operator bool() const noexcept
	{
		return !storage_.empty();
	}
...
};
```
I'm pretty sure this has been the case (since a lot of logic have been built around it). This isn't verified in the unittest tho (needs to be!).
There are no custom move ctor/assignment what I can see (= default), but moving the storage seems to not making the other storage empty.

**Comment by fwsGonzo** [comment]
Turns out moving a raw pointer does not set it to null, because of bad reasons (such as dont pay for what you absolutely expect should happen).

**Comment by AndreasAakesson** [comment]
Some notes are made in #1825. Let's mark this solved until it's not
