### ISSUE TITLE
g++ inline asm randomly fails

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#1826]
Must be clobbered registers, but Ive done everything I can, reading the manuals up and down, and it still keeps failing. One function started randomly working by forcing noinline. Wonder if using Linux-built GNU compiler is not possible.

**Comment by KristianJerpetjon** [comment]
with gcc-8.2.0 we got issues with the ordering of the data from two different functions calling asm code to read registers. 

I would suggest that we rewritine these from beeing asm functions to normal C style volatile to allow the compiler to undestand that the underlaying data is volatile.

**Comment by fwsGonzo** [comment]
Haven't seen this in a while, so closing for now
