### ISSUE TITLE
Building service with size-optimizations garbles memory

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#186]
The size optimization flags `-Os` and `-Oz` flags causes aligniment errors (or something) when building the service. 
* Building `os.a` with these flags is fine, as long as the service is built without them
* Building `test_service.o` with these flags causes crazy behavior:
  * TCP object is suddenly in the wrong address, causing map emplacement to take forever etc.

Thoughts:
* Gnu `ld` doesn't play well with clang's size optimization?
* I noticed that *compiling* with `-flto` causes `ld` to say "unrecognized file format". Related?

**Comment by fwsGonzo** [comment]
Was this fixed with explicit stack-realignment?

**Comment by fwsGonzo** [comment]
Stripped worked for me on my laptop

**Comment by fwsGonzo** [comment]
Can't reproduce this anymore, in any VMM with any combination of stripped and non-stripped service/kernel
