### ISSUE TITLE
Uplink tries to connect before network is fully configured

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#1866]
We see the following happen:

Network shows the normal config done output: 
```
       [ Inet ] Network configured (00:0c:29:8a:3a:6b)
                IP: 		192.168.1.168
                Netmask: 	255.255.0.0
                Gateway: 	192.168.1.1
                DNS Server: 	1.1.1.1
```

Then when the uplink tries to connect it fails, but we see a message about the network finishing it's connection after the uplink begins:

```
     [ Uplink ] [ 2018-08-13T12:28:06Z ] Sending auth request to https://mothership.includeos.org:9090/auth
     [ DHCPv4 ] Configuration complete (eth0)
     [ Uplink ] [ 2018-08-13T12:28:19Z ] Auth failed - Unable to resolve host
     [ Uplink ] Retry auth in 5 seconds...
     [ Uplink ] [ 2018-08-13T12:28:36Z ] Sending auth request to https://mothership.includeos.org:9090/auth
     [ Uplink ] [ 2018-08-13T12:28:36Z ] Auth success (token received)
```

**Comment by AndreasAakesson** [comment]
The message from DHCPv4 is the last thing happening, so we know the network is configured, and the on_config is run by Uplink (sending the auth request).

What happens here is that the first DNS request never gets a reply. Why? I don't know. Maybe it's being sent too early on the network or something.

**Comment by mnordsletten** [comment]
After changing the in-house DHCP settings last week I can't reproduce this anymore. 

I will close this, but keep my eyes open for another case of this happening.
