### ISSUE TITLE
Replace shared_ptr in buffer_t with using a std::vector directly

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#1943]
This will cause quite a big refactor as all copies need to be made std::move, as well as solving the headache of preventing accidental copying of the vector. This change is made for performance reasons, as it removes a level of (pointless) indirection. It will also make all the buffer creation code easier to look at and reason about.

**Comment by alfred-bratterud** [comment]
While we fix this we should also make sure the type is the same on all the `buffer_t`'s, across the OS. E.g. now LiveUpdate has `std::vector<char>` while e.g. fs has `std::vector<uint8_t>`.
