### ISSUE TITLE
Missing directory for linux builds

### ISSUE THREAD

**Issue by perbu** [hioa-cs/IncludeOS#1956]
Hi!
The current dev branch doesn't have the "linux/build" folder created upon installation so lxp-run fails to build. Creating the folder makes everything hunky-dory. The folder could either be in the repo as an empty folder or created by lxp-run.

**Comment by fwsGonzo** [comment]
We can cherry pick this commit into dev to solve this:
https://github.com/hioa-cs/IncludeOS/pull/1951/commits/d90b3fb8789ce77fcd5a927cf5c2d52e101d7027
