### ISSUE TITLE
Bridge43 not working on WSL

### ISSUE THREAD

**Issue by piusogs** [hioa-cs/IncludeOS#1977]
I tried to build includeos in windows subsystem for linux, it build successfully but brigde was not successfully installed... 

      >>> Installing network bridge
      Creating network bridge for IncludeOS
       Using default settings
       Creating bridge bridge43, netmask 255.255.255.0, gateway 10.0.0.1
       ipv6 netmask 64, gateway fe80::e823:fcff:fef4:83e7
       Network bridge already created
       bridge43: error fetching interface information: Device not found
             Configuring network bridge (requires sudo):
        SIOCSIFADDR: No such device
        bridge43: ERROR while getting interface flags: No such device
        SIOCSIFNETMASK: No such device
        bridge43: ERROR while getting interface flags: No such device
        >>> Sorry <<<
        Could not create or configure bridge.

Please it is urgent, we are going to be using it at work, I am to try it out first...

**Comment by fwsGonzo** [comment]
Its because WSL doesnt have TAP/TUN support yet.
Here is the issue: https://github.com/Microsoft/WSL/issues/874
And here is the uservoice page to support the feature: https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/17292841-support-mknod-dev-net-tun-in-wsl

**Comment by piusogs** [comment]
Thanks for the quick response

**Comment by alfred-bratterud** [comment]
Could be worth trying this with [qemu user networking (SLIRP)](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29). It's very limited but doesn't require tap. I guess we can close this issue?

**Comment by piusogs** [comment]
Sure thanks

**Comment by xhimanshuz** [comment]
Getting same error in Arch Linux.
