### ISSUE TITLE
demo_service with solo5 no response

### ISSUE THREAD

**Issue by Kuvesz** [hioa-cs/IncludeOS#1984]
Hi!

The demo_service doesn't seem to send any response back when I'm using solo5/ukvm.
I modified the port the service runs on and changed the config to skip dhcp and instead use 10.0.0.42 as a static ip from the get-go.
I had an issue before where sa_family_t had conflicting definitions, I solved that by commenting out your definition of it, could that have caused it?
From it's terminal it seems that everything is fine, but curl doesn't get the response back:
```
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Memory map: 512 MB addressable:
Solo5:     unused @ (0x0 - 0x200fff)
Solo5:       text @ (0x201000 - 0x403387)
Solo5:     rodata @ (0x403388 - 0x432c2f)
Solo5:       data @ (0x432c30 - 0x687d5f)
Solo5:       heap >= 0x688000 < stack < 0x20000000
                * Initializing Autoconf plugin
   [ Autoconf ] Running auto configure
    [ Netconf ] Configuring network
    [ Network ] Creating stack for Solo5Net on eth0 (MTU=1500)
      [ Inet4 ] Bringing up eth0 on CPU 0
      [ Inet4 ] Network configured (5e:d4:3e:96:0b:b4)
                IP: 		10.0.0.42
                Netmask: 	255.255.255.0
                Gateway: 	10.0.0.1
                DNS Server: 	10.0.0.1
    [ Netconf ] Configuration complete
   [ Autoconf ] Finished
================================================================================
 IncludeOS v0.12.0 (x86_64 / 64-bit)
 +--> Running [ IncludeOS minimal example ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*** Basic demo service started ***
<Service> TCP STATUS:
LISTENERS:
Local	Queued
0.0.0.0:8081	0

CONNECTIONS:
Proto	Recv	Send	In	Out	Local			Remote			State

<Service> @on_connect: Connection 10.0.0.1:37366 successfully established.
<Service> @on_read: 78 bytes received.
<Service> Request:
GET / HTTP/1.1
Host: 10.0.0.42:8081
User-Agent: curl/7.47.0
Accept: */*


<Service> Responding with 200 OK.
<Service> @on_write: 713 bytes written.
```
Also the connection doesn't end (since curl is waiting for a response):
```
CONNECTIONS:
Proto	Recv	Send	In	Out	Local			Remote			State
tcp4	 	 	 	 	10.0.0.42:8081		10.0.0.1:37366		ESTABLISHED
```
I wrote my own http server as well in C and that did the same, it seemed to accept the connection and even try to respond but neither curl nor wget got anything back.
QEMU works fine for both your and my function.
Does anyone have any idea what's happening? 

(Also I'm using 0.12, since I had some nasty problems with even the most basic functions when using 0.13.)

**Comment by alfred-bratterud** [comment]
I can confirm this issue also happens for me on v0.12. I'm getting ping and I do see http transmission with `200 OK` from IncludeOS, but no output from curl, wget etc. Here's a tcpdump:
https://gist.github.com/alfred-bratterud/2f5fb96e8f0b7d6c598c806e29091cfa

@AndreasAakesson can you make sense of it?

**Comment by alfred-bratterud** [comment]
The service is working (e.g. curl responds as expected) for me with v0.13. Would be nice to find the root cause though - and to know why this wasn't picked up by the solo5 test.

**Comment by alfred-bratterud** [comment]
@Kuvesz can you live with #1990 for a little while? If so I think v0.13 would be the best solution - we'll help you get that working if you encounter issues. If you need C++ exceptions or v0.12 for other reasons I can try to have another look at that, otherwise I have #1990 in my scope for the HAL work I'm doing now.

**Comment by Kuvesz** [comment]
Yes I can live with that, I'll post the errors with 0.13 in a different issue.
