### ISSUE TITLE
Recieveing build error when using v0.13

### ISSUE THREAD

**Issue by Kuvesz** [hioa-cs/IncludeOS#1991]
Hi!

I just upgraded from 0.12 to 0.13 (basically a clean install, since I deleted `/usr/local/includeos` before installing) and I'm receiving the following errors when trying to build the demo_service with solo5: (I get roughly the same with the QEMU build.)
It's about 2500 rows, so instead of putting it all in here I made a [pastebin](https://pastebin.com/jL5Pq1qK).
I really can't make much sense of this, not sure why it all happens.

Any help appreciated!

**Comment by fwsGonzo** [comment]
Your default compiler is not C++14 capable. Most likely something old.
Set some environment variables to help CMake determine which compiler you are using. But delete the build folder first.

```
export CC=clang-5.0
export CXX=clang++-5.0
boot . --with-solo5
```

**Comment by alfred-bratterud** [comment]
I also notice you're building without a prefix - I recommend `export INCLUDEOS_PREFIX=somewhere/in/your/home/dir` before installing to avoid issues with e.g. requiring root privileges. With this solution only starting vm's will require root (e.g. in order to interface with the kvm kernel module)

**Comment by Kuvesz** [comment]
I seem to be recieving the same errors with your suggestion @fwsGonzo . Also I'm just testing so I will run as root just be sure either way for now, but thanks for the tip.

**Comment by KristianJerpetjon** [comment]
I think a check that compiler supports c++14 (or 17) has its place in pre.service.cmake

**Comment by Kuvesz** [comment]
I'm just hopelessly stupid. @fwsGonzo you were right, this was the issue, I just forgot to delete the old build folder...
