### ISSUE TITLE
Provide example xml for virsh create

### ISSUE THREAD

**Issue by phifty** [hioa-cs/IncludeOS#2073]
It would be very helpful if an example xml for virsh is included in the repository. It would help to run a compiled image on an hypervisor.

https://libvirt.org/formatdomain.html

**Comment by phifty** [comment]
Ok, I've created a xml that works on CentOS 7

    <domain type="kvm">
      <name>foo</name>
      <memory unit="MiB">256</memory>
      <currentMemory unit="MiB">256</currentMemory>
      <vcpu placement="static">1</vcpu>
      <os>
        <type arch="x86_64" machine="pc">hvm</type>
        <kernel>/srv/foo/chainloader</kernel>
        <initrd>/srv/foo/foo</initrd>
        <boot dev="hd" />
      </os>
      <features>
        <acpi />
        <pae />
      </features>
      <devices>
        <emulator>/usr/libexec/qemu-kvm</emulator>
        <console type="file">
          <source path="/srv/foo/log/foo.log" />
          <target type="serial" port="0" />
        </console>
        <interface type="bridge">
          <source bridge="bridge43" />
          <model type="virtio" />
        </interface>
        <panic model='hyperv' />
      </devices>
    </domain>

**Comment by KristianJerpetjon** [comment]
:+1:
