### ISSUE TITLE
Cannot install includeos

### ISSUE THREAD

**Issue by Pfeifenjoy** [hioa-cs/IncludeOS#2086]
I want to install includeos on my mac. Thus I have cloned it and tried to execute the install.sh script.

I have set the includeos prefix as follows:
```
export INCLUDEOS_PREFIX=~/includeos
```

However I always get the following error:
```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:24 (project):
  The CMAKE_C_COMPILER:

    ~/includeos/includeos/bin/gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:24 (project):
  The CMAKE_CXX_COMPILER:

    ~/includeos/includeos/bin/g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```
This makes sense because not even the folder ~/includeos exists.

Did I miss something?

**Comment by AndreasAakesson** [comment]
The install.sh script on macOS is supposed to run the `install_dependencies_macos.sh`, which will with the help of homebrew install llvm and symlink clang to the bin directory (INCLUDEOS_PREFIX/includeos/bin).
Was the script not run? Or did it fail somewhere? Could be that maybe you need to help it out with creating the folder before hand.
Another very farfetched idea is to maybe use the full path instead (and drop the `~`).

**Comment by Pfeifenjoy** [comment]
Using the full path fixed the error, however I get another error now.

```
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CMakeDetermineCompilerId.cmake:152 (file):
  file failed to open for writing (Permission denied):
```

My guess was, that I have to run the install.sh script as root which results in yet another error.

```
/Users/arwed/Development/IncludeOS/build_x86_64/precompiled/src/PrecompiledLibraries/x86_64/libcxx/include/iterator:432:10: fatal error:
      'Availability.h' file not found
#include <Availability.h>
```

If I find I fix to this I will post it here.

**Comment by Pfeifenjoy** [comment]
I just deleted the repo and cloned it again. Then ran it with the absolute path.
Now it works. Thanks!

**Comment by Pfeifenjoy** [comment]
However I think you should change your install instructions on your webpage
https://www.includeos.org/.

**Comment by AndreasAakesson** [comment]
Good to hear! We're currently making big changes to our build system and updating the documentation in the process. I'll make sure to put an issue on updating the webpage as well, thanks :)
