### ISSUE TITLE
Install --purge-option?

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#222]
We keep getting issues with old scrap, from previous versions of install scripts. I think we should have an `install.sh --purge`-option that will guarantee the removal of everything it has created.

So far, I think the only two "side effects"-folders we have are: `~/IncludeOS_build` and `~/IncludeOS_install`.

**Comment by fwsGonzo** [comment]
Since we now install to a single folder, just removing that folder is enough to fully uninstall, which is great. Closing this
