### ISSUE TITLE
UDP Socket API

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#256]

**Comment by fwsGonzo** [comment]
Still needs ICMP integration as of now, so it we need to expand on ICMP before we can finish UDP (and TCP) sockets

**Comment by alfred-bratterud** [comment]
@fwsGonzo @AndreasAakesson - reviewing UDP-sockets now, are they consistent with TCP sockets?

**Comment by fwsGonzo** [comment]
TCP doesn't have a "Socket API" anymore, so no. It would take some work to make one look like the other, even though UDP is stateless. TCP should be stable now, so we can use that. I imagine SocketUDP or whatever its called will become UDP::Something (its definitely not a connection). But people are not used to any of the things we are doing now anyways. UDP belongs in connectionless communication. Feel free to suggest names.

**Comment by AndreasAakesson** [comment]
What's the status on this issue? Imo the UDP API looks good - it's difficult to make it look more like TCP. Is the issue the TCP API - should it look more like POSIX or can the UDP and TCP look different from each other?

**Comment by fwsGonzo** [comment]
I revamped it already, and we ended up with `UDPSocket` or `SocketUDP` (I dont remember which). And it's probably fine now.
