### ISSUE TITLE
Clean out old trash from git-history

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#266]
There's a lot of old blobs and other clawmarks
- Use the [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) for blobs and binaries
- Remove  `/mod`, and _at least_ `SQLite` from headers.
- Remove old `src/tests` (see #265 )

**Comment by fwsGonzo** [comment]
We already have a newer issue open for this. Duplicate.
