### ISSUE TITLE
Make Bottom and Transmit take specialized packets

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#290]
E.g. IP::bottom should take an IP4-packet, and Ethernet::transmit should take an Ethernet Packet. This goes towards #99

**Comment by fwsGonzo** [comment]
I believe all the shared_ptr's can be trivially forwarded: `class PacketEthernet;` -> `std::shared_ptr<PacketEthernet>`

**Comment by fwsGonzo** [comment]
This has been implemented already. Closing.
