### ISSUE TITLE
TCP:  Buffer output directly to packets

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#293]
TCP is currently using a string as buffer, which gets copied from, into packets. Since #262 is fixed, we can have the TCP socket safely create packets directly, and buffer output into these.

This will remove an extra copy from TCP, making it zero-copy up to the application.

**Comment by AndreasAakesson** [comment]
"Copy buffer" removed in new solution, #370. Replaced with std::queue<shared_ptr<TCP::Packet>>. Not final solution but solves this issue.
