### ISSUE TITLE
VGA Output is a bit sketchy

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#296]
![image](https://cloud.githubusercontent.com/assets/2071766/11429469/8cc311f0-9478-11e5-9e50-65e93efe98a4.png)

**Comment by fwsGonzo** [comment]
Got a crash with e36ced036f1ff09ac903e46b3c58cae8794fd9a6

**Comment by fwsGonzo** [comment]
Can't reproduce this anymore, and the crash was most likely the vmbuilder image size bug

**Comment by alfred-bratterud** [comment]
![image](https://cloud.githubusercontent.com/assets/2071766/13727742/37fab534-e8ff-11e5-89ee-513aabdf4de0.png)
Still getting some artifacts. This is the `./test/vga`-image, under Virtualbox 5.0.3 r102322

**Comment by alfred-bratterud** [comment]
Printing only exclamation marks 10 times pr. second gets me this:
![image](https://cloud.githubusercontent.com/assets/2071766/13727797/30fd664e-e901-11e5-9311-20c919df1c90.png)
and this
![image](https://cloud.githubusercontent.com/assets/2071766/13727800/48e24018-e901-11e5-8d9a-8e94e5fdf75a.png)

**Comment by alfred-bratterud** [comment]
Calling `vga.putEntryAt` and manually computing the rows / columns seem to give consistent results:
![image](https://cloud.githubusercontent.com/assets/2071766/13727876/9f7dca34-e904-11e5-87ea-24e4eae7484d.png)

**Comment by alfred-bratterud** [comment]
Consecutive calls to `vga.newline()` gives me this:
![image](https://cloud.githubusercontent.com/assets/2071766/13727920/4318b400-e906-11e5-91f8-ca7755c08cd1.png)

**Comment by fwsGonzo** [comment]
Hm, I will have to try to do the same thing in my virtualbox

**Comment by alfred-bratterud** [comment]
Note that I made several of the functions in vga public, in order to be able to test them from within the service

**Comment by alfred-bratterud** [comment]
We can call this the Chrismas Sweater Bug. It's supposed to be this boring knit sweater, but somebody went crazy with colored ribbons. It also has holes.
![image](https://cloud.githubusercontent.com/assets/2071766/13728043/91e921ce-e90a-11e5-8f68-7631946db746.png)

**Comment by alfred-bratterud** [comment]
I can't convince myself that it's coincidental that the holes are always 8 bytes wide, and that 8 is [a magic number here](https://github.com/hioa-cs/IncludeOS/blob/master/src/kernel/vga.cpp#L77).

**Comment by fwsGonzo** [comment]
I remember I tried replacing all the xmm with plain old vanilla programming and it made no difference
And I just did your tests on QEMU and everything worked fine

**Comment by fwsGonzo** [comment]
I can't reproduce the issue at home with VirtualBox 5.0.14_Ubuntu r105127

**Comment by alfred-bratterud** [comment]
Ok, attached is my image with artifacts, built on the mac.
[Test.vdi.zip](https://github.com/hioa-cs/IncludeOS/files/170921/Test.vdi.zip)
The exact state of the repo was this: https://github.com/alfred-bratterud/IncludeOS-1/tree/vga_issue, the `./test/vga/`-image

**Comment by alfred-bratterud** [comment]
Confirmed fixed by #427. :+1:

**Comment by alfred-bratterud** [comment]
Very nice sweater:
![image](https://cloud.githubusercontent.com/assets/2071766/13729746/b54b86f2-e93c-11e5-8c08-ddd34be86f3f.png)
