### ISSUE TITLE
using other then C++ languages?

### ISSUE THREAD

**Issue by bubnenkoff** [hioa-cs/IncludeOS#321]
I am interesting of using D, especially web-server http://vibed.org
is it's possible to set up it upon IncludeOS?

**Comment by fwsGonzo** [comment]
No, everything is C++11, with no plans to have separate projects for other languages. It would be a big undertaking to write and maintain from scratch another IncludeOS for other languages.

**Comment by alfred-bratterud** [comment]
That being said: I'm interested in the topic.  D is a compiled language, and if I understand it correctly, links out of the box with C, so it's definitely possible to write a compatibility layer - I guess that would have to be exactly POSIX. Sooner or later, we'll probably want that, but our focus is on a good stable C++ API, and then we might put POSIX on top. Please keep us updated if you pursue this idea further.
