### ISSUE TITLE
Build os.a with cmake

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#340]
This is the missing step somewhere in between `./etc/install_from_bundle.sh` / `./etc/install_osx.sh` and `Make`. You have to figure out where cmake can take over for each.
Use the ninja backend - it's nicer.

**Comment by andreashappe** [comment]
okay, I've started at https://github.com/hioa-cs/IncludeOS/pull/712 , just keep the pull request alive.

**Comment by fwsGonzo** [comment]
This has been implemented, thanks in large to @andreashappe :+1:

**Comment by andreashappe** [comment]
my pleasure, I only did the initial prototype the rest was your work.

Meh, that was also the last time I did some hacking before project-management hell got me again.
