### ISSUE TITLE
Unikernel.org forum and a logo for unikernels!

### ISSUE THREAD

**Issue by amirmc** [hioa-cs/IncludeOS#346]
_[I’m posting this as an issue since there isn’t a mailing list. I hope that’s ok!]_

Hi folks,

I hope everyone had a great new year! I’m Amir and I’ve mostly contributed to MirageOS but I was very happy to see IncludeOS open up its codebase. I also worked with @alfred-bratterud to publish an announcement blog post to help spread the word.

I'd like to tell you about two things I'm working on and get some feedback.  The first is unikernel.org and the second is a logo for unikernels.
### Unikernel.org

Some of you may have noticed a new site called unikernel.org.  This is intended to be a gathering place for development on unikernels and help us ease the process of bringing in new users and contributors across all the projects.

As part of this, there's now a new discussion forum at https://devel.unikernel.org. This should _augment_ the existing sources and help facilitate more cross-pollination and cooperation across unikernel projects. In particular, we will all benefit by working together to solve common problems around configuration, deployment and monitoring.

You can catchup on the discussion that led to the forum [1] and also share feedback about the site in general [2].
### Logo for unikernels

I've also been working towards a logo for unikernels and I'd like to gather feedback from the unikernel community! There's been a 99designs contest running for a while — where designers have submitted just over 400 entries — and a short-list for community feedback is now at https://99designs.co.uk/logo-design/vote-99gjyi (link open until at least 15th Jan).

The reason for creating a logo is that the unikernel approach as a _concept_ has been getting much more attention and by building more of brand around it we can greatly improve the standing of projects and increase adoption!

At this stage, the aim is to gather wider feedback to inform the next step.  The final design will be selected _at a later date_ — after further iteration with designers.  Once a logo is chosen, it will be used on unikernel.org and will help inform the design of the rest of the site.

For more background, you can join the discussion thread [3], read the design brief [4] and look through all the entries [5]. Don't forget to leave feedback [6]!

2016 will be an exciting year for all the unikernel projects and I look forward to getting started!

**Links**

-- unikernel.org --
[1] Discourse forum: https://github.com/Unikernel-Systems/unikernel.org/issues/25
[2] Why unikernel.org: https://devel.unikernel.org/t/why-we-need-unikernel-org/18

-- Logo contest --
[3] Logo discussion: https://devel.unikernel.org/t/a-logo-for-unikernels/47
[4] Logo design brief: https://99designs.co.uk/logo-design/contests/make-fun-logo-open-source-unikernel-projects-562612/brief
[5] All logo entries: https://99designs.co.uk/logo-design/contests/make-fun-logo-open-source-unikernel-projects-562612/entries
[6] Logo short-list: https://99designs.co.uk/logo-design/vote-99gjyi

Best wishes,
Amir

**Comment by alfred-bratterud** [comment]
Hi @amirmc, thanks for the info - this is the right place to post the info as of now. I'll encourage all IncludeOS developers to take a look and provide feedback :-)
