### ISSUE TITLE
Build fails due to missing run.sh

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#347]
The build-script fails with the message from [the Jenkins log](http://jenkins.includeos.org/job/complete_bundle_dev/lastBuild/console): 
`./run.sh: line 2: /home/ubuntu/IncludeOS_install/etc/run.sh: No such file or directory`
This is after the recent streamlining of `run.sh` ( #344 ). It's probably an easy fix.

**Comment by AndreasAakesson** [comment]
This is probably because a typo in `etc/install_from_bundle.sh`. Fixed in #349.

**Comment by AndreasAakesson** [comment]
This is now resolved with #352 & #353.
