### ISSUE TITLE
Certain image sizes causes vm not to boot

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#348]
In a session with @fwsGonzo and @AndreasAakesson we were able to pinpoint that adding a random amount of random code, will cause the image to hang somewhere between the bootloader and `_start`. Reproduce:

Add a certain (yet unknown) amount of triveal for-loops (making sure to avoid compiler optimization, by calling rand() inside). If  you keep adding code, at some point the image hangs. You can then add more code, and it will work again. 

@AndreasAakesson - please commit the exact pinpointed code as a branch somewhere, and document the bug further!

**Comment by AndreasAakesson** [comment]
https://github.com/AndreasAakesson/IncludeOS-HTTP-Service/blob/bug/examples/demo_service/service.cpp#L1746

With the given line/instruction:
`Wrote 1999872 bytes => 3906 sectors to IncludeOS-HTTP-Service.img`
**OK**

Without the given line/instruction:
`Wrote 1967616 bytes => 3843 sectors to IncludeOS-HTTP-Service.img`
**FAIL**

Here it is for now. Will look further into it.

**Comment by fwsGonzo** [comment]
Simply adding +1 sector to the total image size (and nothing else) makes this issue go away. At least, seemingly so. It's possible that the image is incomplete and we don't know it, without deeper inspection.

**Comment by fwsGonzo** [comment]
Fixed by commit cecc485a120af73195c400595de7adc03e05e1c4
