### ISSUE TITLE
Set / determine maximum available memory

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#367]
Currently there's no way of knowing how much physical memory there is, form inside IncludeOS. You'll know from the outside, as this is a parameter to the VM. 

I think the proper way to do it is by inspecting [ACPI tables / RSDP](http://wiki.osdev.org/RSDP). So:

1) Determine maximum memory the proper way 
2) Have `sbrk` enforce this maximium limit, again causing malloc/new to fail gracefully

**Comment by alfred-bratterud** [comment]
Now we A) use multiboot to get a complete memory map or B) ask CMOS. With CMOS you'll only get reported a maximum of 2^16 kb. (~65MiB). With multiboot you get correct values.

**Comment by fwsGonzo** [comment]
We also implemented enforcing memory maximum in `sbrk`. Closing.
