### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#375]
To make it easier for new contributors to get started, let's eliminate the dreaded space vs. tabs-issue and related trivialities.

> "EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles."

http://editorconfig.org/

Basically, if we create an .editorconfig file with our preferred format, we will never have to worry about whitespace in pull requests anymore. (See https://blog.mariusschulz.com/2015/09/05/taming-whitespace-with-editorconfig for a more fleshed out discussion).

**Comment by alfred-bratterud** [comment]
Looks nice - go forth :-)

**Comment by AndreasAakesson** [comment]
:+1:

**Comment by ingve** [comment]
We seem to have a nice mix of styles, a survey revealed the following settings:

| File                                 | Indentation Type | Amount |
| ------------------------------------ | ---------------- | ------ |
| crt/cxxabi/abort_message.cpp         | space            | 4      |
| crt/cxxabi/cxa_aux_runtime.cpp       | space            | 4      |
| crt/cxxabi/cxa_default_handlers.cpp  | space            | 4      |
| crt/cxxabi/cxa_demangle.cpp          | space            | 4      |
| crt/cxxabi/cxa_exception.cpp         | space            | 4      |
| crt/cxxabi/cxa_exception.hpp         | space            | 4      |
| crt/cxxabi/cxa_exception_storage.cpp | space            | 4      |
| crt/cxxabi/cxa_guard.cpp             | space            | 4      |
| crt/cxxabi/cxa_handlers.cpp          | space            | 4      |
| crt/cxxabi/cxa_handlers.hpp          | space            | 4      |
| crt/cxxabi/cxa_new_delete.cpp        | space            | 4      |
| crt/cxxabi/cxa_personality.cpp       | space            | 4      |
| crt/cxxabi/cxa_vector.cpp            | space            | 4      |
| crt/cxxabi/cxa_virtual.cpp           | space            | 4      |
| crt/cxxabi/exception.cpp             | space            | 2      |
| crt/cxxabi/private_typeinfo.cpp      | space            | 4      |
| crt/cxxabi/stdexcept.cpp             | space            | 4      |
| crt/cxxabi/typeinfo.cpp              | space            | 2      |
| crt/cxx_abi.cpp                      | space            | 2      |
| crt/mman.cpp                         | space            | 2      |
| crt/quick_exit.cpp                   | space            | 2      |
| debug/test_disk.cpp                  | space            | 2      |
| debug/test_ipv6.cpp                  | space            | 4      |
| debug/test_service.cpp               | space            | 2      |
| debug/test_tcp.cpp                   | space            | 2      |
| fs/disk.hpp                          | space            | 2      |
| fs/ext4.cpp                          | space            | 2      |
| fs/ext4.hpp                          | space            | 2      |
| fs/fat.cpp                           | space            | 2      |
| fs/fat.hpp                           | space            | 2      |
| fs/fat_sync.cpp                      | space            | 2      |
| fs/filesystem.cpp                    | space            | 2      |
| fs/filesystem.hpp                    | space            | 2      |
| fs/mbr.cpp                           | space            | 2      |
| fs/mbr.hpp                           | space            | 2      |
| fs/memdisk.cpp                       | space            | 2      |
| fs/memdisk.hpp                       | space            | 2      |
| fs/path.cpp                          | tab              | 1      |
| fs/path.hpp                          | space            | 2      |
| fs/vbr.cpp                           | space            | 2      |
| fs/vbr.hpp                           | space            | 2      |
| hw/cpu_freq_sampling.cpp             | space            | 2      |
| hw/dev.hpp                           | space            | 2      |
| hw/disk.hpp                          | space            | 2      |
| hw/disk_device.hpp                   | space            | 2      |
| hw/ide.cpp                           | space            | 2      |
| hw/ide.hpp                           | space            | 2      |
| hw/ioport.hpp                        | space            | 2      |
| hw/nic.cpp                           | space            | 2      |
| hw/nic.hpp                           | space            | 2      |
| hw/pci.hpp                           | space            | 2      |
| hw/pci_device.cpp                    | space            | 2      |
| hw/pci_device.hpp                    | space            | 2      |
| hw/pci_sanos.cpp                     | space            | 2      |
| hw/pic.cpp                           | space            | 2      |
| hw/pic.hpp                           | space            | 2      |
| hw/pic_sanos.cpp                     | space            | 2      |
| hw/pit.cpp                           | space            | 2      |
| hw/pit.hpp                           | space            | 2      |
| include/hw/cpu_freq_sampling.hpp     | space            | 4      |
| kernel/cpuid.cpp                     | space            | 2      |
| kernel/cpuid.hpp                     | space            | 2      |
| kernel/irq_manager.cpp               | space            | 2      |
| kernel/kernel_start.cpp              | space            | 2      |
| kernel/os.cpp                        | space            | 2      |
| kernel/pci_manager.hpp               | space            | 2      |
| kernel/rdrand.cpp                    | space            | 2      |
| kernel/syscalls.cpp                  | space            | 2      |
| kernel/syscalls.hpp                  | space            | 2      |
| kernel/vga.cpp                       | space            | 2      |
| kernel/vga.hpp                       | space            | 2      |
| net/arp.cpp                          | space            | 2      |
| net/arp.hpp                          | space            | 2      |
| net/buffer_store.cpp                 | space            | 2      |
| net/buffer_store.hpp                 | space            | 2      |
| net/dhcp/dh4client.cpp               | space            | 2      |
| net/dhcp/dh4client.hpp               | space            | 2      |
| net/dhcp/dhcp4.hpp                   | space            | 2      |
| net/dns/client.cpp                   | space            | 2      |
| net/dns/client.hpp                   | space            | 2      |
| net/dns/dns.cpp                      | space            | 2      |
| net/dns/dns.hpp                      | space            | 2      |
| net/ethernet.cpp                     | space            | 2      |
| net/ethernet.hpp                     | space            | 2      |
| net/inet.cpp                         | space            | 4      |
| net/inet.hpp                         | space            | 2      |
| net/inet4.hpp                        | space            | 2      |
| net/inet64.hpp                       | space            | 2      |
| net/inet_common.cpp                  | space            | 2      |
| net/inet_common.hpp                  | tab              | 1      |
| net/ip4.cpp                          | space            | 2      |
| net/ip4.hpp                          | space            | 2      |
| net/ip4/icmpv4.cpp                   | space            | 2      |
| net/ip4/icmpv4.hpp                   | space            | 2      |
| net/ip4/packet_arp.hpp               | space            | 2      |
| net/ip4/packet_ip4.hpp               | space            | 2      |
| net/ip4/packet_tcp.hpp               | space            | 2      |
| net/ip4/packet_udp.hpp               | space            | 2      |
| net/ip4/udp.cpp                      | space            | 2      |
| net/ip4/udp.hpp                      | space            | 2      |
| net/ip4/udp_socket.cpp               | space            | 2      |
| net/ip4/udp_socket.hpp               | space            | 2      |
| net/ip6/dhcp6.hpp                    | space            | 2      |
| net/ip6/icmp6.cpp                    | space            | 2      |
| net/ip6/icmp6.hpp                    | space            | 2      |
| net/ip6/ip6.cpp                      | space            | 2      |
| net/ip6/ip6.hpp                      | space            | 2      |
| net/ip6/ndp.hpp                      | space            | 2      |
| net/ip6/packet_ip6.hpp               | space            | 2      |
| net/ip6/udp6.cpp                     | space            | 2      |
| net/ip6/udp6.hpp                     | space            | 2      |
| net/packet.cpp                       | space            | 2      |
| net/socket.hpp                       | space            | 2      |
| net/tcp.cpp                          | tab              | 1      |
| net/tcp.hpp                          | tab              | 1      |
| net/tcp_connection.cpp               | tab              | 1      |
| net/tcp_connection_states.cpp        | tab              | 1      |
| net/tcp_connection_states.hpp        | tab              | 1      |
| net/util.cpp                         | space            | 2      |
| net/util.hpp                         | space            | 2      |
| utility/async_loop.hpp               | space            | 2      |
| utility/delegate.hpp                 | space            | 2      |
| utility/membitmap.hpp                | space            | 2      |
| utility/ringbuffer.hpp               | tab              | 1      |
| utility/signal.hpp                   | tab              | 1      |
| virtio/block.cpp                     | space            | 2      |
| virtio/block.hpp                     | space            | 2      |
| virtio/console.cpp                   | space            | 2      |
| virtio/console.hpp                   | space            | 2      |
| virtio/virtio.cpp                    | space            | 2      |
| virtio/virtio.hpp                    | space            | 2      |
| virtio/virtionet.cpp                 | space            | 2      |
| virtio/virtionet.hpp                 | space            | 2      |
| virtio/virtio_queue.cpp              | space            | 2      |

**Comment by fwsGonzo** [comment]
cxxabi is not part of the project (per se), and we aren't going to modify any of the files there

**Comment by ingve** [comment]
#402 is an initial stab at a common configuration, with what appears to be the most popular settings (type: space, amount: 2)

Here are Editorconfig plugins for common editors:

[Geany](https://github.com/editorconfig/editorconfig-geany#readme)
[Emacs](https://github.com/editorconfig/editorconfig-emacs#readme)
[Sublime](https://github.com/sindresorhus/editorconfig-sublime#readme)
[Textmate](https://github.com/Mr0grog/editorconfig-textmate#readme)

**Comment by alfred-bratterud** [comment]
Nice. One thing though - once I started using this, all my commits to lots of whitespace changes which makes the commit messier. Would be great if you could run this config across all files in one go and commit it as one whitespace cleanup.
