### ISSUE TITLE
Debug macro result in unused parameter warnings when turned off

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#378]
Problem when programming callbacks. An lambda needs to take parameters, but when not implemented by the user, the default will do nothing more than debug. In production, debug will be turned off, and compiler will warn about unused parameters. 
Removing argument name will silence the warning but ruin the debug call.

Example code:

```
PacketDroppedCallback on_packet_dropped_ = [](TCP::Packet_ptr packet, std::string reason) { 
    debug("<TCP::Connection::@PacketDropped> Packet dropped. %s | Reason: %s \n", 
            packet->to_string().c_str(), reason.c_str()); 
};
```

Warnings:

```
../api/net/tcp.hpp:826:65: warning: unused parameter 'packet' [-Wunused-parameter]
                PacketDroppedCallback on_packet_dropped_ = [](TCP::Packet_ptr packet, std::string reason) { 
                                                                              ^
../api/net/tcp.hpp:826:85: warning: unused parameter 'reason' [-Wunused-parameter]
                PacketDroppedCallback on_packet_dropped_ = [](TCP::Packet_ptr packet, std::string reason) { 
                                                                                                  ^
```

**Comment by alfred-bratterud** [comment]
Good point. We should consider finding a templatized version of `debug` that allows the parameters to enter the compiler, but not the final object turned off.

**Comment by fwsGonzo** [comment]
There are several ways to work around this with preprocessor macros or customizing the debugging for a specific module. I think I'll just close this. Look at BufferStore or VirtioNET driver.
