### ISSUE TITLE
Service name should support whitespace

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#386]
Currently the service name is set in the makefile (i.e. in seed). This name is both used as name of the image, implying that it shouldn't contain whitespaces, but we also want to be able to display a nice human-readable name inside the service after boot.  I suggest making a second variable in the Makefile for this.

**Comment by fwsGonzo** [comment]
There also needs to be a way for a user to set these things the first time, and then changing it later that is easier than changing variables in a makefile. Preferrably through some JSON or meta file.

**Comment by fwsGonzo** [comment]
Fixed in 1270e426e8c5d0fe524d73a12e5c434c07b5c813
