### ISSUE TITLE
seed/build: Slice Makefile into smaller modular parts

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#399]
When creating a new service from seed, the Makefile also needs to get copied. The same Makefile exists in a lot of place, and updates to the build process will break all services using the old copy.

Makefile should be separated into smaller "modules" and included in the main Makefile. This will also reduce the amount of redundant code.

**Comment by fwsGonzo** [comment]
This is the biggest problem right now, and why its so annoying to "create" system tests

**Comment by alfred-bratterud** [comment]
I can have that done tomorrow

**Comment by fwsGonzo** [comment]
@alfred-bratterud +1 :tophat:

**Comment by fwsGonzo** [comment]
Support added in 1270e426e8c5d0fe524d73a12e5c434c07b5c813 and https://github.com/hioa-cs/IncludeOS/commit/99252bb1da2ca1d52917f8f1be1918bf76898f79

**Comment by alfred-bratterud** [comment]
I changed this to use `include` in order to get the service name right. Works nicely.

**Comment by fwsGonzo** [comment]
https://github.com/hioa-cs/IncludeOS/commit/0d7bd46c00ffd0ed767f6b658d943c5d9271f59c via this

**Comment by AndreasAakesson** [comment]
+1 :cake:
