### ISSUE TITLE
Timers don't work in debug mode

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#411]
Timers don't fire when IncludeOS is built with `make debug`.

**Output:**

```
TESTING Timers 
                + Enabling IRQ 0, mask: 0xfffa
[ IRQ manager ] Updated subscriptions: 0x1 irq: 0
===* <IRQ !> IRQ 0 Pending: 0x1x. Count: 2
=RQ !> IRQ 0 Pending: 0x1x. Count: 2
========================================
 IncludeOS v0.8.0-rc.1-1-ga5fed3c-dirty
 +--> Running [ Timers Test Service ]
~
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
.... // this continues forever
```

**How to reproduce:**
`make debug` and make a service using `hw::PIC::instance().onTimeout()` *(i used [/test/timers/](https://github.com/hioa-cs/IncludeOS/tree/master/test/timers))*

**Comment by alfred-bratterud** [comment]
@AndreasAakesson thanks for reporting. Can you please verify that it in fact continues forever?

**Comment by AndreasAakesson** [comment]
Sure, I'll come back with a log when forever has past.

**Comment by alfred-bratterud** [comment]
Excellent, just what I wanted to hear :-)

**Comment by alfred-bratterud** [comment]
(Please note that you might be able to circumvent the problem using [transfinite induction](https://en.wikipedia.org/wiki/Transfinite_induction) on a deterministic mathematical model of the problem. You could probably figure out how to do that in finite time and you could then proceed to evaluate if it's a useful approach)

**Comment by AndreasAakesson** [comment]
Actually it looks like I'm wrong with timers not firing, but it takes a few minutes (Virtualbox, slow console output, could be it). Will give it a try on qemu on Ubuntu VM.

*around 3 minutes into forever:*

```
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
One second passed...
1sec. PULSE 
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
Hey - this is a std::function - it knows about integers:
1
2
3
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
...
```

Thanks for the tip btw!

**Comment by alfred-bratterud** [comment]
Oh, right. One possibility is that the millisecond interval is too hard to achieve in emulated mode. If this bug turns out to just happen nested inside virtualbox, which means it only happens in *emulation* mode, we should close it. Forgot to mention my platform: IncludeOS nested inside Ubuntu, inside Virtualbox, on MacAir. 

Oh - and thanks for thanking me about the tip! (...then you invite me to talk more about infinity by saying...)

**Comment by AndreasAakesson** [comment]
Infinity on my Ubuntu VM was much much shorter.
```
================================================================================
TESTING Timers 
                + Enabling IRQ 0, mask: 0xfffa
[ IRQ manager ] Updated subscriptions: 0x1 irq: 0
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 2
================================================================================
 IncludeOS v0.8.0-rc.1-8-gee618a5
 +--> Running [ Timers Test Service ]
~
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
* <IRQ !> IRQ 0 Pending: 0x1x. Count: 3
** <IRQ notify> __irqueue 0 Count: 2
** <IRQ notify> __irqueue 0 Count: 1
** <IRQ !> IRQ 0 Pending: 0x1x. Count: 1
 <IRQ !> IRQ 0 Pending: 0x1x. Count: 1
// ends here
```

**Comment by AndreasAakesson** [comment]
.... Oh - and thanks for thanking me for thanking you about the tip! :shipit:

**Comment by alfred-bratterud** [comment]
YES! :mortar_board: :joy:

**Comment by alfred-bratterud** [comment]
That gave me a good idea - we should modify the TCP protocol to do an _n_-way handshake. We could then guarantee that the handshake would complete in finite time, and guarantees are excellent!

**Comment by alfred-bratterud** [comment]
I'm not able to replicate this on hardware (trident1) - in fact it works like a charm, even with all debugging symbols *and* all the debug info printing from inside the IRQ-handlers proper.
