### ISSUE TITLE
Need solution to dynamically increase buffer pool

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#412]
See this TODO: https://github.com/hioa-cs/IncludeOS/blob/master/src/net/buffer_store.cpp#L50

**Comment by alfred-bratterud** [comment]
Not sure about this one. Might be better to make a clean interface for apps to set this limit to what they want. Thoughts are welcome.

**Comment by fwsGonzo** [comment]
Right now if the bufferstore cannot give out packets, it could just allocate the buffers on heap. This will work automatically as buffers that dont belong to the bufferstore are assumed to be heap-allocated.

**Comment by fwsGonzo** [comment]
Already implemented
