### ISSUE TITLE
How to test VGA

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#425]
As the issue title suggests: How do you test VGA, exactly?

**Comment by alfred-bratterud** [comment]
Yes, it's hard, but I think we can use the `-curses`-option, and route the output to a file.

**Comment by alfred-bratterud** [comment]
It's also possible to use `VBoxManage` to take a screenshot :-) then that can be compared to other screenshots.

**Comment by fwsGonzo** [comment]
This is not going to be worthwhile. Closing.
