### ISSUE TITLE
Network writable and free packet slots

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#432]
Top level programs and TCP itself needs to use a round-robin algorithm to write content out on the network, but only when the network is writable

Idea:
So, the network says it has 48 packet slots free, this is propagated maybe to Ethernet then Arp
Arp writes its packets **and subtracts from total free the number of new packets sent**. If there is still free packet slots, the IP4 layer is called with the number, and it again uses round-robin to send one packet from each connection until either no packets can be sent or the number of free slots is 0.

No connection should be able to hog the entire bandwidth
We also need to account for virtio wanting to kick only when X packets are scheduled in some time limit (TCP window) to avoid context switches

On the userland end:
The user gets callback "writable," and the user then tries to write data from bytestream. The write function returns how many bytes were written as usual, and the user knows nothing of any "number of free packet slots."

**Comment by AndreasAakesson** [comment]
This sounds like a good idea. So do the TCP just shove packets down to the network layer (IP), or will the TCP receive some kind of signal/callback? From whom?

**Comment by AndreasAakesson** [comment]
TCP got updated with something along the lines what you're suggesting:

[Event for when there is free packets](https://github.com/hioa-cs/IncludeOS/blob/dev/src/net/tcp.cpp#L188) or [write directly if none waiting](https://github.com/hioa-cs/IncludeOS/blob/dev/src/net/tcp.cpp#L197)
[Connection get an offer with available packets](https://github.com/hioa-cs/IncludeOS/blob/dev/src/net/tcp_connection.cpp#L122)

(There is an logical error where connection doesnt get poped and put in back of queue, update on the way)

**Comment by fwsGonzo** [comment]
Solved https://github.com/hioa-cs/IncludeOS/issues/475 with https://github.com/hioa-cs/IncludeOS/pull/476
