### ISSUE TITLE
OSX missing unistd.h

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#435]
Running `$ ./etc/install_osx.sh` fails:
```
>>> Compiling the vmbuilder, which makes a bootable vm out of your service
~/IncludeOS/vmbuild ~/IncludeOS
In file included from vmbuild.cpp:18:
In file included from /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/../include/c++/v1/vector:264:
/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/../include/c++/v1/__config:23:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^
1 error generated.
make: *** [vmbuild.o] Error 1
cp: vmbuild: No such file or directory
```
This means we can't build the vmbuilder on OSX the way things are.

**Comment by alfred-bratterud** [comment]
This is due to missing XCode command line tools. Installing like so:
`$ xcode-select --install` made the `vmbuilder` build without a hitch

**Comment by alfred-bratterud** [comment]
@AndreasAakesson If you could add a test in the script to verify that this is installed, that'd be great, and we could close the issue.

**Comment by AndreasAakesson** [comment]
This is closable
