### ISSUE TITLE
BufferStore should return "null"-shared-pointer if it can't create packet

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#445]
currently we're just panicking if we run out of buffers in the bufferstore. Even if we decide to increase the bufferstore dynamically, we should handle the case where we're out of memory. 

This should be implemented [here](https://github.com/hioa-cs/IncludeOS/blob/master/src/net/buffer_store.cpp#L58)

**Comment by fwsGonzo** [comment]
The bufferstore could also just create the packet on heap.. the system already supports this. However, if the bufferstore runs out of packets, it means that some layer took too many packets for itself and didn't wait for signal from the driver to continue sending.

**Comment by fwsGonzo** [comment]
It does return null unless bufferstore chaining is enabled, in which case it just creates more packets
