### ISSUE TITLE
smalldisk and terminal_disk.o missing

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#449]
1. When building with `./src/$ make test` you need to have a `./src/smalldisk`-file present. 
2. Since the latest terminal / FS PR #448 you also need `./src/kernel/terminal_disk.o` present 

This should be automatic

**Comment by fwsGonzo** [comment]
https://github.com/hioa-cs/IncludeOS/pull/451/commits/271b83dea87f02d2f31d3b819f9f9c51bb217261
Should fix it
