### ISSUE TITLE
Fetch CPUinfo in OS

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#45]
Now OS::_CPU_mhz is just set to 2500. OS::uptime needs this to calculate seconds

**Comment by alfred-bratterud** [comment]
This was put in ages ago - @fwsGonzo can you point me to the current cpuinfo code?

**Comment by fwsGonzo** [comment]
`kernel/cpuid.cpp` I believe the CPU info stuff is now
