### ISSUE TITLE
Protect kernel code

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#458]
Static data and code can be write-protected by setting the proper segments as read-only. This helps enforce and prove that services are immutable. To properly do this we will also have to align the static sections to pages, so that the code segment is properly separated from the rest. We can also move exception frames into this part.

**Comment by fwsGonzo** [comment]
Although, would it have any effect when we are running everything in ring-0 (?) I guess we would have to write-protect it from the VMM-side... and how do we do that?

**Comment by alfred-bratterud** [comment]
Yes, that's the problem - if we want normal protection we can't run in ring0, and that means lots of context switches. I've heard that you can indeed do this from the VMM-side, but I seriously doubt that we'll find a simple solution that works well across all hypervisors we want to support...
