### ISSUE TITLE
Porting disk-creation to Mac

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#460]
All of the disk tests use gnu/posix programs to automate creation of disk images and filesystems. This means the tests can't be run automatically on OSX. The tests need to be ported in a simple manner so as not to introduce too much difference between the tests.

Additionally, the disks that aren't linked into the service image will have to be added to VirtualBox using its image-creation API.

**Comment by AndreasAakesson** [comment]
For creating FAT disks on OS X:
`hdiutil create -help`

Example FAT16 40MB (with volume name):
`hdiutil create -megabytes 40 -volname MyFAT16Disk -o test_disk.dmg`

FAT32 100MB:
`hdiutil create -megabytes 100 -fs MS-DOS -fsargs "-F 32" -o test_disk.dmg`

**Comment by fwsGonzo** [comment]
Already implemented with diskbuilder, and cmake memdisk image most likely works too.
