### ISSUE TITLE
IDE: Improve test

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#466]
The [IDE test](https://github.com/hioa-cs/IncludeOS/blob/dev/test/IDE/service.cpp) needs to:
- [ ]  Use the `CHECK` / `CHECKSERT`-macros or `lest`, and indicate success / failure (see the [STL test](https://github.com/hioa-cs/IncludeOS/blob/dev/test/STL/service.cpp) for examples) 
- [ ]  Demonstrate how to use a secondary hard drive (i.e.  `qemu-system-i386 -hdb ...`)
- [ ]  Demonstrate that the custom interrupt handler does not mess up the context, in particular floating point / SIMD registers. A start would be to have a compute-heavy algorithm start and run continously, directly after calling async read, to make sure the CPU is working with e.g. floating point registers when the interrupt happens.

**Comment by alfred-bratterud** [comment]
@yrakcaz are you willing to take responsibility for this one?

**Comment by alfred-bratterud** [comment]
See also #438

**Comment by yrakcaz** [comment]
Hi,

Really sorry for that I wasn't available for a while, but sure I'll take this one.

Cheers.
