### ISSUE TITLE
UDP sockets

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#467]
* Rename UDP sockets to something that isn't "socket" or "connection." (Or maybe just keep calling it socket since its one-way?)
* Add sendq to UDP, so that we don't blow up memory with internal buffering

**Comment by fwsGonzo** [comment]
The socket class is now renamed to UDPSocket, and Socket<> is removed. Also in the process of adding callback write, which is the first step before I can add the send queue.

* Use suggested MTU for virtual networks (1400-something). There is no way to know what the largest datagram size is for any network.
* Rewrite the packet-giveaway strategy so that its fair towards UDP and other protocols. To do that, we need to make a count of the number of packets an upper layer wants to use.
* Add send queue for UDP, which is used with packet-giveaways to always keep the line busy, while at the same time make the OS do nothing when its idle.

Using only UDP, it should be possible to have the OS sleep during low-activity. Don't think its possible with TCP.

**Comment by fwsGonzo** [comment]
This is the current implementation:
https://github.com/hioa-cs/IncludeOS/pull/474
https://github.com/hioa-cs/IncludeOS/pull/478
https://github.com/hioa-cs/IncludeOS/pull/479

**Comment by AndreasAakesson** [comment]
I like this :+1:
