### ISSUE TITLE
A system for Fair distribution of packets

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#475]
Due to the finite amount of packets in the system, and the finite amount of bandwidth we can transmit, we have to fairly distribute the free packets to all layers that have a send queue.

One way to do this, is that to let UDP distribute all free packets until it no longer needs to send, then give the rest to TCP. That way, UDP will have fewer github issues open compared to TCP.

**Comment by AndreasAakesson** [comment]
:-1:

**Comment by fwsGonzo** [comment]
Jokes aside, we now have a simple fair packet-disbtribution algorithm.
See: https://github.com/hioa-cs/IncludeOS/pull/476

**Comment by AndreasAakesson** [comment]
Lookin' good!
