### ISSUE TITLE
Intercepting Clib calls

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#486]
Using certain techniques we can intercept and replace standard C-library with high performance versions. Enabled with `-DINTERCEPT` and only for modules including `#include <intercept>`, for example.

Intercepts are created with good old magic: `#define memcpy(a, b, c)    faster_memcpy(a, b, c)`

The first intercepted function would be memcpy, replaced with facebook's custom memcpy: https://github.com/facebook/folly/blob/master/folly/memcpy.S

EDIT: Oops, theres a %rax in there, guess we have to find another replacement memcpy.

**Comment by fwsGonzo** [comment]
Proper example for 80686 (LGPL):
http://osxr.org:8080/glibc/source/sysdeps/i386/i686/memcpy.S

**Comment by alfred-bratterud** [comment]
Bad link

**Comment by fwsGonzo** [comment]
Both links works fine here for me
