### ISSUE TITLE
Direct boot from virtio block-device

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#5]
Issue #4 shows how to make openstack hook up the disk image to the IDE bus so that our bootloader works. However, it would be nice if we could boot from a virtio drive directly. It seems to come up as a scsi-disk and PCI device no. 4. Seems hard to do this properly, directly from the bootloader without probing the PCI. Maybe people are using BIOS-calls to do it- the BIOS will know which devices are present and also which one is the boot device. In that case it's back to 16-bit loading.

**Comment by fwsGonzo** [comment]
http://wiki.qemu.org/Features-Done/VirtioBlkBoot

**Comment by fwsGonzo** [comment]
This is currently solved by using grub, I believe. Closing
