### ISSUE TITLE
test/transmit fails

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#526]
Error output from the log can be seen here: https://jenkins.includeos.org/job/test_transmission/14/console

It fails while complaining about packet order.

```
<Test.py> Performing UDP test 1
<Test.py> Sent:     Douche
<Test.py> Received: Received 'Douche
'. Expect 2400 packets in 1s

<Test.py> FAIL: Packet order is wrong
```

This error was introduced in one of these commits: https://jenkins.includeos.org/job/test_transmission/10/
Prior to this we had a successful run of the transmit test.

**Comment by alfred-bratterud** [comment]
I think this is packet loss over the wire, and to be expected. The test is meant to verify that the transmission buffering works, and that after buffering, packets still come out in the right order.

**Comment by fwsGonzo** [comment]
If this issue resurfaces I will reopen this

**Comment by mnordsletten** [comment]
This is not really solved. More than 50% of the tests I perform result in the `packet order is wrong error.`
