### ISSUE TITLE
Install from bundle doesn't work on forks

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#539]
`install_from_bundle.sh` want's to download the bundle with the latest tag (release). It also fetch/updates the tags. Problem is when using a fork, the tags doesn't exist on the fork, but the script will try to fetch the new tags from my fork `origin`, not the main repo `upstream`.
To solve this I first need to pull the tags from main repo, and then push them to my fork.

```
git fetch --tags upstream
git push --tags origin
etc/install_from_bundle.sh
```

How can we make this automate this?

**Comment by mnordsletten** [comment]
Something like this might work:

```git ls-remote --tags https://github.com/hioa-cs/IncludeOS.git | grep -oP "tags/\K(.*)$" | grep -v "{" | sort -n -t . -k 1 -k 2 -k 3 | tail -n 1```

This will always get the latest tag from the original IncludeOS repo. There were very limited options in processing the output though, so I had to grep that myself.

**Comment by AndreasAakesson** [comment]
Sounds good 👍

**Comment by AndreasAakesson** [comment]
Solution:
```
git fetch --tags https://github.com/hioa-cs/IncludeOS.git master
```

**Comment by mnordsletten** [comment]
Still an issue. I think our hotfixes are messing this up. This post describes our issue pretty well I think.

http://www.xerxesb.com/2010/12/20/git-describe-and-the-tale-of-the-wrong-commits/
