### ISSUE TITLE
FAT::readFile causing CPU exception/reading outside RAM

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#547]
Either qemu crashes, or CPU exception occurs on `FAT::readFile(const string&, on_read_func)`, when using **VirtioBlk** FAT16 disk.

**Comment by fwsGonzo** [comment]
Recommend making readFile inline using stat() and read() instead of it being virtual interface function.

**Comment by AndreasAakesson** [comment]
:+1:
