### ISSUE TITLE
Automatically build ubuntu package out of toolchain + libs

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#55]
This way we can
1. Skip the 1 hour compilation of gcc toolchain every time we start on a new machine
2. Get all the dependencies right (i.e. GCC w. C++11 for vmbuild, qemu etc.)
3. Make proper binary releases

**Comment by andreashappe** [comment]
you could use cmake (cpackage) to build debian/ubuntu packages after the build system was switched over..

**Comment by andreashappe** [comment]
speaking of which: https://github.com/hioa-cs/IncludeOS/pull/918 . Still lacking many features, but at least a debian deb file with include files, libraries is build. Next step would be to add all mandatory dependencies.
