### ISSUE TITLE
install_from_bundle.sh fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#553]
/etc/install_from_bundle.sh fails in Ubuntu 14.04 because it is unable to install clang 3.8.

Quite possibly related to http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html

**Comment by alfred-bratterud** [comment]
Thanks! I'll try to add back support for clang 3.6 and have the makefile detect which one you have.

**Comment by alfred-bratterud** [comment]
This is now fixed in my fork. Will merge as soon as all the tests pass.
