### ISSUE TITLE
vboxrun.sh should make sure host-only network is defined

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#555]
With a fresh install of virtualbox `vboxrun.sh` doesn't work unless you create a host-only network. It's sufficient to just create a default one, using _virtualbox_->_preferences_->_Network_->_Host-only Networks_ and then clicking the little green "+ nic" icon:
![screen shot 2016-06-06 at 20 56 06](https://cloud.githubusercontent.com/assets/2071766/15833911/1f73d384-2c29-11e6-8127-385c3aeb07d9.png)

**Comment by AndreasAakesson** [comment]
#297 duplicate. Close on of these?
