### ISSUE TITLE
vboxrun.sh has problems overwriting an existing vm

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#556]
This is at least the case when you don't specify a new name for the VM (second parameter to `vboxrun.sh`)

Recreate on OSX (Mac Mini late 2014, El Capitan):
- With no vm's in virtualbox, buil `./seed` and start it with `./etc/vboxrun.sh IncludeOS_service.img`. This works fine. 
- Power off the VM
- Leaving the VM as it is in virtualbox, building `./examples/demo_service` and running it with `./etc/vboxrun.sh IncludeOS_Demo_service.img` will cause a failing / hanged vritualbox vm.

![screen shot 2016-06-06 at 21 37 29](https://cloud.githubusercontent.com/assets/2071766/15835133/e35f0246-2c2e-11e6-8c45-61bae403c471.png)
- It seems you have to _Apple_->_Force quit_->_Virtualbox VM_ in order to get it to go away.
- Completely removing the VM from virtualbox (right click VM, "Remove"->"Delete all files") will cause new problems (the VM seems to start but it's unresponsive - looks like it will still use the old image).

Using a unique VM-name (2nd param to `./etc/vboxrun.sh`) for each image seems to work consistently. I suggest making `./etc/vboxrun.sh` use the image name as virtualbox VM-name by default instead of "IncludeOS_test".

**Comment by AndreasAakesson** [comment]
Good idea. Also make the first argument (target image) mandatory?

**Comment by fwsGonzo** [comment]
It supports running several of the same instance now, I believe
