### ISSUE TITLE
TCP interprets ethernet padding as data

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#565]
TCP calculates the size of the data in a packet as `net::Packet::size()` minus the size of all headers. This means that ethernet padding will be interpreted as data. The correct behavior is to ask the IP header for IP data size, i.e. IP segment length minus size of IP header, and then subtract the size of the TCP header.  (Thanks to @sfrode at Basefarm for the packet trace that pointed us in this direction)

**Comment by AndreasAakesson** [comment]
I'm on it!

**Comment by AndreasAakesson** [comment]
This is probably solved
