### ISSUE TITLE
./test/term is broken

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#568]
The double-brackets in Inet-config is a quick fix, which makes it run. But there are also some minor issues:
- It looks like a carriage return is missing after printing the banana logo
- Typing e.g. Ctrl+c will make the prompt disappear. 

This is all very minor but the terminal is so cool it would be nice to get some polish on it :-)

**Comment by fwsGonzo** [comment]
The control-characters are abit more involved to add support for.. At some point, maybe. I fixed the carriage return as it was a modification to the inline multistring.

**Comment by alfred-bratterud** [comment]
Cool, so close?

**Comment by fwsGonzo** [comment]
No, I will revisit this later and see if I can't figure out what Ctrl+C actually does in telnet. Just keep in mind it could be a "telnet thing" and could be unrelated to the terminal. We'll see.
