### ISSUE TITLE
Latest hotfix breaks ICMP

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#575]
The latest hotfix to TCP/IP makes an assertion in IPv4 to fail on ICMP ping. In other words no pinging for the next few minutes while somebody cooks up a hotfix.

**Comment by fwsGonzo** [comment]
Fixed with https://github.com/hioa-cs/IncludeOS/pull/576/commits/84d59c7d7ea531e00b4325adaa5b7aa12d1126e6
