### ISSUE TITLE
Improving serial port output 

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#597]
We've experienced very slow serial port output in Virtualbox. @AndreasAakesson found [this thread](https://groups.google.com/forum/#!topic/osv-dev/u-bxKf2qIKY) from OSv which has some nice pointers. In particular we should look into utilizing the serial port buffer better, and reduce time in the busy-wait loop.

**Comment by AndreasAakesson** [comment]
This command made some big improvements on the speed. Around 10x as fast.
`VBoxManage setextradata VM_NAME "VBoxInternal/Devices/serial/0/Config/YieldOnLSRRead” 1`
