### ISSUE TITLE
Dev branch several commits behind master branch

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#616]
At this point in time the dev branch is 24 commits behind the master branch. This is not optimal in any way. The dev branch should always be up to date or before the master branch. I'll just list up some issues around this:

- Synchronization of tags. If a tag is only created at the master branch and never merged into the dev branch is this ok? One issue here is shown in #615.
- To avoid having to cherrypick certain hotfixes we should be creating a hotfix branch that we merge into both master and dev. 
- When looking at the possibilities of merging master with dev @AndreasAakesson found several merges that he meant were already present in the dev branch. Before a potential merge we should look into this. Performing a test merge with a temporary dev-branch as @matiashf suggested sounds like a good idea.
- We have a lot of branches that can be closed:
  - https://github.com/hioa-cs/IncludeOS/tree/remove_libgcc
  - https://github.com/hioa-cs/IncludeOS/tree/mini_demangle
  - https://github.com/hioa-cs/IncludeOS/tree/new_device_system
  - https://github.com/hioa-cs/IncludeOS/tree/hotfix

Moving forwards I suggest that we adopt the general guides for git branches as described here: [a-successful-git-branching-model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by fwsGonzo** [comment]
I believe we already do this, with the exception of the tag accident. The problem was most likely that people hotfixed dev instead of master, and then cherry-picked from dev to master. Is that correct?

**Comment by mnordsletten** [comment]
Yeah that is correct. Though creating a release branch that branches off from dev when the features wanted have been agreed upon is also a good idea. 

After I fixed the tag issue yesterday we aren't really reliant on tags anywhere any more. This issue can be closed, but hopefully our git workflow can improve over time.

**Comment by fwsGonzo** [comment]
Will keep this in mind :+1:
