### ISSUE TITLE
Install into a hidden directory instead of ~/IncludeOS/

### ISSUE THREAD

**Issue by matiashf** [hioa-cs/IncludeOS#621]
Installing into the non-hidden directory `~/IncludeOS` is unnecessary. The install directory should be hidden, i.e. `~/.IncludeOS`.

**Comment by matiashf** [comment]
Workaround:
```
mkdir ~/.IncludeOS
export INCLUDEOS_INSTALL_LOC=~/.IncludeOS/
```

**Comment by matiashf** [comment]
Also, `INCLUDEOS_INSTALL` and `INCLUDEOS_INSTALL_LOC` are used inconsistently.

**Comment by mnordsletten** [comment]
Just to clear up in those environment variables you mention, these are the variables that we will be using in all our scripts as soon as I get time to clear them up:

```
Env variable            -   Description                             -   Default value

INCLUDEOS_SRC           -   Github repository                       -   $HOME/IncludeOS
INCLUDEOS_BUILD         -   Build dir used for install.sh           -   $HOME/IncludeOS_build
INCLUDEOS_INSTALL       -   Directory of installation               -   $HOME/IncludeOS_install
INCLUDEOS_INSTALL_LOC   -   Parent folder of INCLUDEOS_INSTALL      -   $HOME
```

Today we have a large mix of `INCLUDEOS_INSTALL` and `INCLUDEOS_HOME` both pointing to the same thing. `INCLUDEOS_INSTALL` is the one we will be using moving forwards. Which does make #234 not valid anymore.

**Comment by fwsGonzo** [comment]
Progress on this?

**Comment by andreashappe** [comment]
Hm. in the cmake-based build everything is initially build within the (local) build directory. `make install` heeds CMAKE_INSTALL_PREFIX so the install directory can be chosen by the user. There's also an option to build .deb files (for now) which would be installed in the typical LInux bin, lib, share/includeos subdirectories. Does this help?

**Comment by fwsGonzo** [comment]
https://github.com/hioa-cs/IncludeOS/pull/1178
