### ISSUE TITLE
Packet buffer gets deallocated before being sent

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#624]
With the newly introduced `new/delete` method to create packets, and the abscene of bufferstore, results in some packet buffers being deallocated before being sent on virtio. The result is virtio sending bogus data out on the wire.
`VirtioNet::enqueue(net::Packet_ptr)` is the last place where the `Packet_ptr` exists, and if virtio doesn't send the packet fast enough, some other function may overwrite the given memory where the packet existed.
Solution is to rewrite and reimplement bufferstore again.

**Comment by fwsGonzo** [comment]
Fixed in https://github.com/hioa-cs/IncludeOS/pull/627
Among other things also fixes problem with deque TX packets in virtionet, hidden by deque access pattern
