### ISSUE TITLE
Synflood before starting OS causes bufferstore depletion

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#632]
.. which again causes panic

Note that the bufferstore can deplete at any time on any version of the OS. This is an architectural problem that needs thought, and we have to implement something we can know will keep the BufferStore replenished in all realistic scenarios. Right now the most likely reason for depletion is that there is no time alotted for responding with packets, in the end because of IRQ priority and how slow nested guests are.

**Comment by fwsGonzo** [comment]
Implementing TCP backlog will help prevent this issue

**Comment by AndreasAakesson** [comment]
Haven't given it a try after #683, possibly fixed.

**Comment by fwsGonzo** [comment]
Seems to be solved now
