### ISSUE TITLE
Stress test sometimes fails

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#635]
```
color.FAIL(name_tag+"Python socket failed while getting memsize: "+e)
TypeError: cannot concatenate 'str' and 'error' objects
```
On latest dev the stress test failed to read memory used by VM, which is unrelated to the OS or the test. There is also a syntax error as seen in the text above. Maybe `str(e)` fixes it.

**Comment by mnordsletten** [comment]
I just tested a clean installation on both Ubuntu 16.04 and 14.04 and the test worked on both of them. Now on the test machine running Ubuntu 14.04 that performs the pipeline build there are problems. I'll look into what is causing the issues there.

**Comment by fwsGonzo** [comment]
The stress test is stalling on something, but the VM service is still working just fine. To verify this we can connect from outside to all services and do the test "manually" from start to end, while the vmrunner script is stalled. Eventually the vmrunner script ends because the test times out.

**Comment by mnordsletten** [comment]
The code in the original post here is fixed, but during the day the error that @fwsGonzo describes was introduced.

The best clue to follow is that the `get_mem` function in the vmrunner.py script is struggling to get output when the script is running. I tested in a manual python session while running the test and I was able to get reliable output from the VM.

**Comment by fwsGonzo** [comment]
I managed to make the stress test work again by disabling the separated MSI-X handlers for VirtioNet. I'm guessing some kind of deadlock happens. Just have to figure out how it can happen now.

I'll close this for now.
