### ISSUE TITLE
vmrunner handler will not interrupt

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#639]
When trying to abort a test using <CTRL-C> the following error is returned:

``` 
File "../vmrunner.py", line 88, in handler
    thread.interrupt_main()
NameError: global name 'thread' is not defined
```

This refers to the following line in the vmrunner script: https://github.com/hioa-cs/IncludeOS/blob/dev/test/vmrunner.py#L88
Simply doing an `import thread` and trying to abort a running VM results in a loop of `Process interrupted` messages.

I didn't have more time to figure this out, so written here to remember to look into this.

**Comment by AndreasAakesson** [comment]
Is this still the case?

**Comment by mnordsletten** [comment]
I believe this has been fixed by the following commit: 
https://github.com/hioa-cs/IncludeOS/commit/f0b44210e92fee7ede99dedbc43ca6f781a21c80

I'll close this issue.
