### ISSUE TITLE
Dynamically change disk layout for bochs

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#64]
The vmbuilder used to create a disk image with a permanent ~1MB size (32 tracks/cyls@63spt 1 head). This has now changed due to #62. `vmbuild` will still create a disk image with a valid CSH-layout, where we always use 63 spt (which is the "standard") and 1 head, for simplicity. But, the number of cylinders will now change according to the size of the image (it will be the smallest sufficient number of cylinders).

This means that in order to get bochs to work, we either have to :
1. Change './etc/bochsrc' dynamically, each time we rebuild an image
2. Get bochs to work with a more modern type of image, i.e. one that can be created by `qemu-image` in `./seed/convert_image` (It should be able to run `vmdk` images, but the one I make now didn't work right off the bat)
3. Set bochs to boot with a command-line parameter specifying the disk layout, and have that paramter be output to a file by vmbuild.

**Comment by fwsGonzo** [comment]
We are using other platforms where this is not a thing, with other disk formats. Closing.
