### ISSUE TITLE
test: STREAM incomplete

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#650]
- Missing new test system (test.py)
- Missing README
- *Gives warnings on compile*
- Service do not exit
- Missing SUCESS/FAIL criteria

Does this belong inside `/test` - or is it benchmarking?

Also, see #441

**Comment by fwsGonzo** [comment]
Moved to its own example folder (again) called STREAM. Now also uses OS uptime, instead of slow second-based gettimeofday.
