### ISSUE TITLE
test: exceptions incomplete

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#654]
- Missing new test system (test.py)
- Missing SUCCESS
- Needs to be updated with either macro or lest test framework (preferred)

**Comment by AndreasAakesson** [comment]
@matiashf will take a look at this one

**Comment by matiashf** [comment]
I simplified the exception tests to make them fit with [lest](https://github.com/martinmoene/lest), and now they only test for exception types, not exception descriptions. Will they have to be extended to compare exception strings?

@alfred-bratterud rewrote the tests in 03c097690aaf125cc0ee62060c0d847e683f94e1, but it's unclear what the rationale was compared to the previous version in 9cd39f3c8842b62c24f13355c5c11cdce006e7a8.

**Comment by AndreasAakesson** [comment]
I see no reason not to compare exception strings, as the current version does that. Just extend it as you see fit if you come up with more scenarios 👍

**Comment by AndreasAakesson** [comment]
Fixed with #677
