### ISSUE TITLE
Document and enforce standard format for commit message subject lines

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#655]
Commit messages should indicate which major component the commit makes changes to.

Good commit messages have a subject line that **starts with the name of the major component** that is modified by the commit:

- virtionet: Increased buffers for packets
- test: Update bufferstore test
- crt: Manually realign heap to at least 16 byte boundary

Bad commit message subject lines makes it hard to quickly understand which component the commit applies to: 

- Improved gettimeofday
- Fixed errors to pass build tests

Reviewers should feel free to **require** contributors to improve their commit message subjects. Over time we should set up automatic enforcement.

**Comment by AndreasAakesson** [comment]
🔨  Move to wiki and close?

**Comment by ingve** [comment]
I think it already was moved to/integrated with wiki text, and people seem to use the desired commit message format now, so yes.

https://github.com/hioa-cs/IncludeOS/wiki/Contributing-to-IncludeOS
