### ISSUE TITLE
Jenkins spams when non-whitelisted users makes a PR

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#678]
When a non-whitelisted user makes a pull request, jenkins will add the following message for *each* test it tries to run (currently 6 times):

> Can one of the admins verify this patch with one of the following commands:

>- "ok to test" to accept this pull request for testing
- "test please" for a one time test run
- "add to whitelist" to add the author to the whitelist

See #677.

**Comment by mnordsletten** [comment]
This is a known issue and there was a pull request to jenkins that was supposed to fix this, but the development of the fix stopped for some unknown reason. At the moment this does not happen that often, but I will look into this at a later date.

**Comment by mnordsletten** [comment]
One idea is to have multiple credentials where only one of the pull request build jobs actually has permission to write comments. -> Note for later.

**Comment by mnordsletten** [comment]
I've attempted to fix this issue. We will see if it actually works the next time some non-whitelisted user makes a pull request.

**Comment by mnordsletten** [comment]
Confirmed as fixed here: https://github.com/hioa-cs/IncludeOS/pull/734
