### ISSUE TITLE
Build `os.a` for Linux

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#715]
We've decided to do unit testing outside of IncludeOS which essentially means we need to build most of the OS for Linux. We might not get all the classes built but we can start with a separate make target that builds what it can, for Linux in 64 bit. All of that can then be linked in with unit tests. This will also be a good first step towards a userspace version of IncludeOS.

**Comment by fwsGonzo** [comment]
This is done in another repo already

**Comment by ricarkol** [comment]
Hi @fwsGonzo @alfred-bratterud , what's the other repo? would love to be able to run acorn on linux (for perf comparison purposes).

**Comment by fwsGonzo** [comment]
https://github.com/fwsGonzo/UserlandNetworking

I haven't implemented a high-performance TAP driver yet, so the performance isn't great

**Comment by ricarkol** [comment]
Thanks! no worries

**Comment by fwsGonzo** [comment]
I just updated it to latest dev, but I don't see any acorn so I guess I never ported it fully
I've ported "everything" else, so I'm hopeful it's not much to do

**Comment by fwsGonzo** [comment]
With https://github.com/fwsGonzo/UserlandNetworking/commit/9f59cc21856a806349004c20d456b3d5d62a170d I've ported Acorn to Linux, but implementing MemDisk still remains, not to mention you will need to generate the FAT image that memdisk reads from

**Comment by ricarkol** [comment]
Thanks @fwsGonzo , will give it a try.
