### ISSUE TITLE
Universal access point for IP stacks

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#718]
Currently the user instantiates IP stacks directly on top of devices. This works fine but not if you have separate modules that needs access to the same IP stack - then you'd be replacing the delegates for that device to point to your new stack and essentially stealing traffic from the other. I suggest a template factory method in `Inet` that provides static instances of say `Inet<DRIVER>(Nic<I, DRIVER>)`. The factory should be the only allowable way to create Inet instances.

**Comment by alfred-bratterud** [comment]
@AndreasAakesson close?

**Comment by AndreasAakesson** [comment]
Since we only got IPv4 stack atm, I guess it's okay. What do you think?
It's not all the way down to `net::Inet`, but `net::Inet4`

**Comment by alfred-bratterud** [comment]
That's for 2017 :-)
