### ISSUE TITLE
Silence vmbuilder output

### ISSUE THREAD

**Issue by fwsGonzo** [hioa-cs/IncludeOS#722]
It's creating alot of output, and is primarily relevant for debugging complicated problems, or adding new features which require modifying images. Having an option to silence it, and making that option the default behavior, would help reduce logspam.

**Comment by alfred-bratterud** [comment]
Yes, It should have a `-v` / `--verbose`

**Comment by fwsGonzo** [comment]
Solved with https://github.com/hioa-cs/IncludeOS/commit/4acf575f8cf5f81468f8c3eeb6e860a2a34ce4b2
