### ISSUE TITLE
install.sh displays error messages on OS X

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#784]
When running install.sh using OS X, the first couple of lines of output are error messages:

```
./install.sh: line 4: lsb_release: command not found
./etc/install_build_requirements.sh: line 12: return: can only `return' from a function or sourced script

###################################
IncludeOS installation for Mac OS X
###################################
```
(...bazillion lines of normal output...) before the installation succeeds.

We should probably not perform `lsb_release -is` unconditionally since it does not exist in OS X.

**Comment by AndreasAakesson** [comment]
Solved
