### ISSUE TITLE
After UDP burst in stress test get_mem does not answer immediately.

### ISSUE THREAD

**Issue by mnordsletten** [hioa-cs/IncludeOS#805]
With the current release 0.9.0 when running the stress test on an ubuntu medium flavor on openstack the test tends to hang after the initial UDP burst.

To reproduce just run a stress test from the 0.9.0 release build. I don't know how hardware dependent this bug is.

In order to solve this hanging issue a sleep was added to the get_mem function, before it attempts to send the `memsize\n` string to the VM. 

I don't view this as a long time solution as there seems like the VM is overloaded by the UDP burst, and is not able to answer the following TCP request. It might also be possible that this is a python specific issue.

**Comment by fwsGonzo** [comment]
Is this still the case?

**Comment by ciarancourtney** [comment]
Hi @fwsGonzo not sure if this is related, but I found a similar issue when running [these tests](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2936), after a while the VM becomes unresponsive and QEMU goes to 100% CPU

**Comment by fwsGonzo** [comment]
I saw your PR. Nice stuff. It's hard to say from here whether or not it still happens. We have services that have been running for a long time while being bombarded. So, perhaps we need to setup a machine whos only purpose is to run UDP or ARP bombardment against an instance.
