### ISSUE TITLE
OS::version() returns v?.?.?

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#814]
`OS_VERSION` in os.hpp is never defined by the looks of it - `OS::version()` returns "v?.?.?"

**Comment by fwsGonzo** [comment]
Needs some git foo turned into a define in the seed makefile

**Comment by fwsGonzo** [comment]
Solved by storing the OS version permanently in OS class. https://github.com/hioa-cs/IncludeOS/commit/9db5676214e0a52d0b106731bb2e9fbc93e557d5
