### ISSUE TITLE
Statman suggestions

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#825]
It showed to be really useful.

Some QoL improvements is:
- Since there is a singleton instance on `Statman::get()`, there should also be a helper for `Statman::create`
- Adding units (ENUM?) to Statman would be really helpful. For example when serving a stat with `bytes` as JSON to some kind of client, it would be possible to format it correctly.
- Maybe add some `const` getters as well - currently not possible to operate as "read only".

**Comment by fwsGonzo** [comment]
Has this been fixed?

**Comment by AnnikaH** [comment]
Not fixed, will add it to my todo-list

**Comment by fwsGonzo** [comment]
Stats already take up alot of space, so unless we want to shorten name length (48->40 bytes) adding units will be hard. With 32 cpu cores there already isn't enough room for stats.
