### ISSUE TITLE
Installing on Arch Linux x64 ("No section header named .multiboot" error on test.sh execution)

### ISSUE THREAD

**Issue by SuperV1234** [hioa-cs/IncludeOS#837]
I am trying to install IncludeOS on an Arch Linux x64 machine _([`uname -a` output](https://gist.githubusercontent.com/SuperV1234/1f1958ae99b430ae59bece28e3646bbc/raw/baee92e69b2ad185678d9debf8c67bc893ae282b/output_uname_a.txt))_.

I installed the following packages available in Arch's package manager...

```
pacman -S jq qemu libc++ bridge-utils nasm
```

and executed the `./etc/install_from_bundle.sh` and `sudo ./etc/create_bridge.sh` commands, which both completed successfully.

Upon running `./test.sh`, however, I get the following error output:

```
~/temp/IncludeOS/examples/demo_service ~/temp/IncludeOS
/usr/lib/hardening-wrapper/bin/clang++ -target i686-elf -MMD -mstackrealign -msse3 -fstack-protector-strong -O2 -DOS_TERMINATE_ON_CONTRACT_VIOLATION -Wall -Wextra  -c -m32 -std=c++14 -I~/IncludeOS_install/libcxx/include -Ia~/IncludeOS_install/api/sys -I~/IncludeOS_install/newlib/include -I~/IncludeOS_install/api -I~/IncludeOS_install/mod/GSL  -D_LIBCPP_HAS_NO_THREADS=1 -D_GNU_SOURCE -o service.o service.cpp
/usr/lib/hardening-wrapper/bin/clang++ -target i686-elf -mstackrealign -msse3 -fstack-protector-strong -O2 -DOS_TERMINATE_ON_CONTRACT_VIOLATION -Wall -Wextra  -c -m32 -std=c++14 -I~/IncludeOS_install/libcxx/include -I~/IncludeOS_install/api/sys -I~/IncludeOS_install/newlib/include -I~/IncludeOS_install/api -I~/IncludeOS_install/mod/GSL  -D_LIBCPP_HAS_NO_THREADS=1 -D_GNU_SOURCE -DSERVICE_NAME="\"IncludeOS Demo Service\"" -o .service_name.o ~/IncludeOS_install/service_name.cpp
\n>> Linking service with OS
ld -nostdlib -melf_i386 -N --eh-frame-hdr --script=~/IncludeOS_install/linker.ld --defsym _MAX_MEM_MIB_=128 --defsym=__stack_rand_ba=`date +%s` ~/IncludeOS_install/crt/crtbegin.o ~/IncludeOS_install/crt/crti.o ~/IncludeOS_install/multiboot.o service.o .service_name.o ~/IncludeOS_install/drivers/virtionet.o  ~/IncludeOS_install/os.a ~/IncludeOS_install/libcxx/libc++.a ~/IncludeOS_install/libcxx/libc++abi.a ~/IncludeOS_install/os.a ~/IncludeOS_install/newlib/libc.a ~/IncludeOS_install/newlib/libm.a ~/IncludeOS_install/libgcc/libgcc.a ~/IncludeOS_install/crt/crtend.o ~/IncludeOS_install/crt/crtn.o  -o Demo_Service
strip -S Demo_Service
\n>> Building Demo_Service.img
~/IncludeOS_install/vmbuild Demo_Service ~/IncludeOS_install/bootloader
terminate called after throwing an instance of 'Elf_exception'
  what():  No section header named .multiboot
make: *** [~/IncludeOS_install/Makeseed:145: service] Aborted (core dumped)

INSTALL FAILED ON COMMAND: make
```

What is causing this issue? I'd like to experiment with IncludeOS and contribute to the project.

**Comment by fwsGonzo** [comment]
Strange! Looking at the command-line there is nothing I can see that would strip anything more than just the debug symbols.
I can see that you have at least gotten your ELF binary linked, so how about you try and run it directly like this? Just to see if there is nothing wrong with the program binary itself:
```
qemu-system-x86_64 -nographic -kernel Demo_Service
```
It will run the service as a multiboot kernel directly on qemu (with no network devices attached unfortunately)
.. however if it should work, at least you can try to copy our commandline from qemu_cmd.sh and run the service directly from your own shell script!

**Comment by fwsGonzo** [comment]
So, the only obvious thing here that does anything to sections (assuming vmbuilder is doing things right), it would be the strip command. You can try just removing the strip part of the service makefile located in `IncludeOS_Install/Makeseed` probably line 145 which says:
```
strip $(STRIPPED) $(SERVICE)
```
Try commenting it out or remove it and then try to make again

The strip command in your case was doing -S which is (per manual) remove debug information, which is all the sections starting with `.debug`.

**Comment by SuperV1234** [comment]
Thanks for the assistance.

---

> Just to see if there is nothing wrong with the program binary itself: 
>
>      qemu-system-x86_64 -nographic -kernel Demo_Service

The binary file runs, but nothing is displayed on my terminal - it seems like it's frozen. I have to kill the `qemu` process *(it does not respond to signals)*. What is supposed to happen? Is there any chance Arch's `qemu` installation is broken?

I tried running it with the arguments generated by `qemu_cmd.sh` *(`qemu-system-x86_64 -nographic -kernel Demo_Service`)* with the same result.

---

> You can try just removing the strip part of the service Makefile located at  IncludeOS_Install/Makeseed probably line 145, which says:
>
>     strip $(STRIPPED) $(SERVICE)

Still throws the same `Elf_exception`.


---

> You can also verify the existence of the multiboot section with:

>     readelf --sections Demo_Service

Here's the output. There is no `.multiboot` section:

```bash
There are 18 section headers, starting at offset 0x166188:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        00200054 000054 0dee6b 00 WAX  0   0 16
  [ 2] .init             PROGBITS        002deec0 0deec0 00000f 00  AX  0   0  1
  [ 3] .fini             PROGBITS        002deed0 0deed0 00000a 00  AX  0   0  1
  [ 4] .got              PROGBITS        002deee0 0deee0 000718 04  WA  0   0  4
  [ 5] .ctors            PROGBITS        002df600 0df600 00003c 00  WA  0   0  4
  [ 6] .dtors            PROGBITS        002df640 0df640 00000c 00  WA  0   0  4
  [ 7] .rodata           PROGBITS        002df660 0df660 00a154 00   A  0   0 32
  [ 8] .gcc_except_table PROGBITS        002e97b4 0e97b4 00ebec 00   A  0   0  4
  [ 9] .eh_frame_hdr     PROGBITS        002f83a0 0f83a0 0038a4 00   A  0   0  4
  [10] .eh_frame         PROGBITS        002fbc44 0fbc44 012c48 00   A  0   0  4
  [11] .data             PROGBITS        0030e8a0 10e8a0 0035bc 00  WA  0   0 32
  [12] .jcr              PROGBITS        00311e5c 111e5c 000004 00  WA  0   0  4
  [13] .bss              NOBITS          00312000 111e60 006548 00  WA  0   0 4096
  [14] .comment          PROGBITS        00000000 111e60 000099 01  MS  0   0  1
  [15] .shstrtab         STRTAB          00000000 1660fa 00008b 00      0   0  1
  [16] .symtab           SYMTAB          00000000 111efc 015a50 10     17 1281  4
  [17] .strtab           STRTAB          00000000 12794c 03e7ae 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)
```

**Comment by LordAro** [comment]
FWIW, I can't reproduce this on my Arch install - on a brief inspection from the `test.sh` output, could `/usr/lib/hardening-wrapper/bin/clang++` possibly be related? My output just uses the standard `/usr/bin/clang++`

**Comment by haikarainen** [comment]
@LordAro I'm no expert with qemu, but I've had that exact error plenty of times before. Unrelated to includeOS ofc.

**Comment by fwsGonzo** [comment]
Did you manage to resolve this somehow? We had a similar issue with cmake, but that was most likely related to the order in which we linked the modules, and you are just using the standard build method afaik.

**Comment by SuperV1234** [comment]
Sorry for the very late reply. Today I cloned `IncludeOS` from scratch and tried to run `./install.sh`. I got some compilation errors:

```cpp
kernel/cpuid.cpp:42:21: error: using declaration cannot refer to a scoped enumerator
    using Register::EAX;
          ~~~~~~~~~~^
kernel/cpuid.cpp:43:21: error: using declaration cannot refer to a scoped enumerator
    using Register::EBX;
          ~~~~~~~~~~^
kernel/cpuid.cpp:44:21: error: using declaration cannot refer to a scoped enumerator
    using Register::ECX;
          ~~~~~~~~~~^
kernel/cpuid.cpp:45:21: error: using declaration cannot refer to a scoped enumerator
    using Register::EDX;
          ~~~~~~~~~~^
```

[*(Full log here.)*](https://gist.github.com/SuperV1234/cc8e36d7cc5fde911e30b992d23fbfa7)

**Comment by SuperV1234** [comment]
#1004 should fix the compiler error. (I also opened #1003 to avoid reinstalling packages on Arch Linux over and over).

**Comment by SuperV1234** [comment]
Even with #1004 merged, the `./install.sh` script fails:

```cpp
vmbuild.cpp:29:10: fatal error: 'gsl/gsl' file not found
#include <gsl/gsl>
         ^
1 error generated.
```

---

`locate gsl | grep gsl$` prints out:

```bash
/home/vittorioromeo/Repos/IncludeOS/mod/GSL/gsl
/home/vittorioromeo/Repos/IncludeOS/mod/GSL/gsl/gsl
/home/vittorioromeo/Repos/IncludeOS/test/mod/gsl
```

**Comment by SuperV1234** [comment]
IncludeOS tries to use `ifconfig`, which [**is deprecated in Arch Linux**](https://wiki.archlinux.org/index.php?title=Core_utilities&redirect=no#ip):

> Note: You might be familiar with the ifconfig command, which was used in older versions of Linux for interface configuration. It is now deprecated in Arch Linux; you should use ip instead.

**Comment by SuperV1234** [comment]
The build step fails as well:

```
>>> Building IncludeOS
~/Repos/IncludeOS/src ~/Repos/IncludeOS
MMD -target i686-elf -mstackrealign -msse3 -fstack-protector-strong -D_STACK_GUARD_VALUE_=1481668290 -DNO_DEBUG=1 -DOS_TERMINATE_ON_CONTRACT_VIOLATION -D_GNU_SOURCE -O2 -Wall -Wextra  -c -m32 -march=i686 -I../api/sys -I/home/vittorioromeo/IncludeOS_install/newlib/include -Iinclude -I../api -o util/memstream.o util/memstream.c
make: MMD: Command not found
make: [Makefile:197: util/memstream.o] Error 127 (ignored)
MMD -target i686-elf -mstackrealign -msse3 -fstack-protector-strong -D_STACK_GUARD_VALUE_=1481668290 -DNO_DEBUG=1 -DOS_TERMINATE_ON_CONTRACT_VIOLATION -D_GNU_SOURCE -O2 -Wall -Wextra  -c -m32 -march=i686 -I../api/sys -I/home/vittorioromeo/IncludeOS_install/newlib/include -Iinclude -I../api -o crt/c_abi.o crt/c_abi.c
make: MMD: Command not found
make: [Makefile:197: crt/c_abi.o] Error 127 (ignored)
MMD -target i686-elf -mstackrealign -msse3 -fstack-protector-strong -D_STACK_GUARD_VALUE_=1481668290 -DNO_DEBUG=1 -DOS_TERMINATE_ON_CONTRACT_VIOLATION -D_GNU_SOURCE -O2 -Wall -Wextra  -c -m32 -march=i686 -I../api/sys -I/home/vittorioromeo/IncludeOS_install/newlib/include -Iinclude -I../api -o crt/string.o crt/string.c
make: MMD: Command not found
make: [Makefile:197: crt/string.o] Error 127 (ignored)
\n>> Building the OS library
ar rcs os.a kernel/start.o kernel/kernel_start.o kernel/syscalls.o kernel/interrupts.o kernel/os.o kernel/os_stdout.o kernel/cpuid.o kernel/memmap.o kernel/irq_manager.o kernel/pci_manager.o kernel/elf.o kernel/terminal.o kernel/terminal_disk.o kernel/vga.o kernel/context.o kernel/context_asm.o kernel/profile.o kernel/profile_intr.o kernel/timers.o kernel/rtc.o util/memstream.o util/async.o util/statman.o util/logger.o crt/c_abi.o crt/string.o crt/quick_exit.o crt/cxx_abi.o crt/mman.o hw/ide.o hw/pit.o hw/pic.o hw/pci_device.o hw/cpu_freq_sampling.o hw/ps2.o hw/serial.o hw/cmos.o hw/drive.o hw/acpi.o hw/apic.o hw/apic_timer.o hw/ioapic.o hw/apic_asm.o hw/apic_revenant.o hw/msi.o hw/pci_msi.o virtio/virtio.o virtio/virtio_queue.o net/ethernet/ethernet.o net/inet_common.o net/ip4/arp.o net/ip4/ip4.o net/tcp/tcp.o net/tcp/connection.o net/tcp/connection_states.o net/tcp/rttm.o net/tcp/listener.o net/ip4/icmpv4.o net/ip4/udp.o net/ip4/udp_socket.o net/dns/dns.o net/dns/client.o net/dhcp/dh4client.o net/buffer_store.o net/inet4.o fs/disk.o fs/filesystem.o fs/mbr.o fs/path.o fs/ext4.o fs/fat.o fs/fat_async.o fs/fat_sync.o fs/memdisk.o apic_boot.o
ar: util/memstream.o: No such file or directory
make: *** [Makefile:155: os.a] Error 1
\n>> Installing IncludeOS
cp -r ../api /home/vittorioromeo/IncludeOS_install/
mkdir -p /home/vittorioromeo/IncludeOS_install/drivers
cp -r drivers/*.o /home/vittorioromeo/IncludeOS_install/drivers
mkdir -p /home/vittorioromeo/IncludeOS_install/platforms
cp -r platforms/*.o /home/vittorioromeo/IncludeOS_install/platforms
cp bootloader /home/vittorioromeo/IncludeOS_install
cp boot/multiboot.o /home/vittorioromeo/IncludeOS_install
cp os.a /home/vittorioromeo/IncludeOS_install
cp: cannot stat 'os.a': No such file or directory
make: *** [Makefile:170: install] Error 1
```

`MMD` is not available on my system after installing the IncludeOS dependencies. Are you looking for `mmd` in [mtools](https://www.archlinux.org/packages/extra/i686/mtools/files/)? If so, `mtools` should be added as a dependency in the `pacman` invocation step.

**Comment by fwsGonzo** [comment]
it looks like no compiler is being set by the script, or maybe your CXX and CC is not set before using cmake build system?

**Comment by SuperV1234** [comment]
Oh, I see what `MMD` was referring to now *(I feel dumb)*. After a `make clean` clang was detected correctly. By the way, `src/Makefile` is setting `CC` and `CPP`:

```makefile
CC  = $(shell command -v clang-3.8 || command -v clang-3.6)
CPP = $(shell command -v clang++-3.8 || command -v clang++-3.6 || command -v clang++)
```

`CC` is never properly set on Arch Linux because there is no `clang-3.8` or `clang-3.6`. It should be:

```makefile
CC  = $(shell command -v clang-3.8 || command -v clang-3.6 || command -v clang)
```

I'll open a PR.

**Comment by fwsGonzo** [comment]
We are using cmake on dev, so the PR would temporarily fix master, which is soon to be updated!
If you want to test our cmake, feel free. It should be ready for usage now

**Comment by SuperV1234** [comment]
#1005 should fix the `$(CC)` issue on Arch Linux. With #1003, #1004 and #1005 merged all together, and after calling `cd ./src/ && make clean && make` again... the "OS-library" builds successfully.

Calling `./install.sh` builds everything successfully, but `ifconfig` is not available on Arch Linux anymore, so it still fails:

```
>>> Creating a virtual network, i.e. a bridge. (Requires sudo)
sudo: ifconfig: command not found
>>> Sorry <<< 
Could not create or configure bridge. 
```

**Comment by fwsGonzo** [comment]
Was this fixed?

**Comment by SuperV1234** [comment]
@fwsGonzo should I try `dev` or `master`?

**Comment by fwsGonzo** [comment]
I think it's present on master, but it's probably easiest for us to help if you work on dev :+1:

**Comment by SuperV1234** [comment]
```bash
git clone https://github.com/hioa-cs/IncludeOS/ -b dev
cd ./IncludeOS
./install.sh
```

It install packages and then fails without any useful error message:

```text
>>> Calling install_from_bundle.sh script
>>> Sorry <<< 
Could not install from bundle. 
```

**Comment by fwsGonzo** [comment]
I wonder what the install script even does these days.. is this on Arch linux?


Try to go into IncludeOS repo root,
```
export CC=clang-whatever.youhave
export CXX=clang++-whatever.youhave
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=~/includeos
make -j install
```

**Comment by SuperV1234** [comment]
Executing `boot .` produces an error:

```text
  File "/home/vittorioromeo/includeos/bin/boot", line 18
    print "Couldn't find IncludeOS installation. If you installed to a non-default location (e.g. not " + default_loc + ") please set the environment variable INCLUDEOS_PREFIX to point to this location."
                                                                                                      ^
SyntaxError: invalid syntax
```

This happens because `python3` is invoked by default on Arch Linux instead of `python2`. If I change the first line of the script to `#/usr/bin/python2`, the error is replaced with:

```text
ImportError: No module named jsonschema
```

This happens because `install.sh` uses `pacman` to install `python-jsonschema`, which installs the `python3` version of the module. 

What you want to install are:

* `python2-jsonschema`
* `python2-psutil`

After doing that, `boot .` **works properly!**

Unforunately, booting `256_color_vga` opens up a QEMU window that gets stuck on "Booting from ROM...".

Booting `snake` doesn't open any QEMU window.

**Comment by fwsGonzo** [comment]
Yea, many of the examples haven't been updated yet to use boot, but as long as it starts.. you are good to go.. The python prerequisites are installed with install.sh normally, I guess. Maybe you can PR us a fix to make it less likely to use python3 versions?

**Comment by SuperV1234** [comment]
@fwsGonzo: #1129
