### ISSUE TITLE
Syntax error in bootloader.asm on Mac OS X

### ISSUE THREAD

**Issue by d-weber** [hioa-cs/IncludeOS#839]
➜  src git:(master) nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016

➜  src git:(master) nasm -f bin -o bootloader boot/bootloader.asm -g
boot/bootloader.asm:131: error: expression syntax error
boot/bootloader.asm:133: error: expression syntax error
boot/bootloader.asm:135: error: expression syntax error
boot/bootloader.asm:163: error: expression syntax error

on OS X 10.11.3

Tried some quick fixes but failed.

**Comment by fwsGonzo** [comment]
I don't know what that's all about but according to NASM's website the latest version is `2.12.02`. I would try using the latest version.

**Comment by ingve** [comment]
Did you run `install.sh` and still end up with an old version of NASM? When i run install.sh on OS X, NASM version 2.12.01 is installed.

**Comment by d-weber** [comment]
Hi Guys
The problem was that my path do not included brew first.

The fix is 
````
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.zshrc
````

Ty

**Comment by mnordsletten** [comment]
I have the same issue as you @d-weber on a pretty fresh install of OSX. We will see if we can solve this in a general way.

**Comment by d-weber** [comment]
@mnordsletten yup, i think the brew default config is the issue here
