### ISSUE TITLE
cannot stop service after running test.sh

### ISSUE THREAD

**Issue by fangxian** [hioa-cs/IncludeOS#841]
There is no response by pressing ctrl-c on ubuntu16.04. 
I have to close the terminal.

**Comment by RicoAntonioFelix** [comment]
Running the example is akin to running the python interpreter, by pressing `Ctrl-c` doesn't exit the interpreter. To do that you provide a special command that it understands as `exit` which is the `exit()` function.

To exit the service you'll need to enter `Ctrl-a,x`, which is to press Ctrl `and` a `then` x

**Comment by fangxian** [comment]
It works. thank you
