### ISSUE TITLE
VirtioBlk cannot handle large files

### ISSUE THREAD

**Issue by danieloneill** [hioa-cs/IncludeOS#845]
Once apparently 3 blocks (or inodes) are read, additional reads are queued. Queue runs, but never "ships", meaning the callback provided to read() is never reached. Small files (under 3 blocks or so) worked, but for larger files a different codepath is followed.

I've traced it to viritoblk.cpp:194
```
  // only ship more if we have nothing more queued (??)
  if (inflight == 0) {
    // if we have lots of free space and jobs, ship many
    bool shipped = false;
    while (free_space() && !jobs.empty()) {
      auto* vbr = jobs.front();
      jobs.pop_front();
      shipit(vbr);
      shipped = true;
    }
    if (shipped) req.kick();
```

Unfortunately, inflight is never initialised anywhere, so the number (while refcounted perfectly otherwise) most likely never lands on 0.

Pull request submitted with (the world's smallest) patch: https://github.com/hioa-cs/IncludeOS/pull/844

(Also, the integration test for virtio_block uses the service.cpp file itself, which at 2.9k doesn't follow the 'large file' codepath, and hence wouldn't trigger the issue. Additionally, acorn skirted the issue largely as well, as the files are all small! Still, this bug can be confirmed by simply creating a disk image for the virtio_block integration test with a larger (64k or so) file and adjusting the test to reference the larger file.)

**Comment by AndreasAakesson** [comment]
Wow, nice find 😃  🍰  Thanks!

**Comment by alfred-bratterud** [comment]
Thanks @danieloneill - nothing like simple solutions. Happily merged to master :-)
