### ISSUE TITLE
split code up by architecture and platform

### ISSUE THREAD

**Issue by GravisZro** [hioa-cs/IncludeOS#854]
If it's intended for includeOS to be on IoT systems, you will need to segment your code so that code can be added to support different architectures and platforms without every contributor having to grok the entire source tree.

I'd like to see raspberry pi zero support added but in it's current state, includeOS is unlikely to get the code contributions required.

**Comment by ingve** [comment]
A Hardware Abstraction Layer and an architecture/platform-based code split-up is on the roadmap. We would love it if you join our [Gitter chat](https://gitter.im/hioa-cs/IncludeOS) if you have any specific thoughts on this that you'd like to discuss.

**Comment by fwsGonzo** [comment]
This has been implemented and is on master now :+1:
