### ISSUE TITLE
std::random_device crashes VM

### ISSUE THREAD

**Issue by Voultapher** [hioa-cs/IncludeOS#863]

**Comment by johannes** [comment]
I had the same issue. I created my own device based on C's rand() like this:

```C++
class TestDevice {
public:
  using result_type = decltype(rand);

  result_type operator()() const { return rand(); }
  double entropy() const { return 0; }
  static constexpr result_type min() { return 0; }
  static constexpr result_type max() { return RAND_MAX; }
};
```

At least in my little game library this worked nicely.

**Comment by fwsGonzo** [comment]
If you want to fix it, just go to syscalls.cpp and strcomp the filename argument for `open()` towards `/dev/urandom` or `/dev/random`, then return something useful, like by using rdrand instruction.

**Comment by johannes** [comment]
Well open has to return some for of file handle and then read() and others have to be implemented, along with some file handle tracking etc.

**Comment by fwsGonzo** [comment]
You could make the handle for the random device(s) just some constant value :) unless that won't work
