### ISSUE TITLE
macOS: Install GNU binutils with homebrew

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#876]
There is a [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/binutils.rb) for binutils. Since we're already depending on homebrew for  building on macOS, it would be nice to avoid doing all the work with downloading and building binutils ourselves.

What we need:
- `ld`
- `ar`
- `objcopy`
- `strip`

What looks to be the problem with installing with homebrew is that the formula doesn't support `--enable-ld=yes` (seems to be related to [this issue](https://github.com/Homebrew/legacy-homebrew/issues/50393#issuecomment-201474361)).

This is how we're building it today (not sure everything is needed but `target` and `enable-ld`):
`./configure --program-prefix=$LINKER_PREFIX --prefix=$BINUTILS_DIR --enable-multilib --enable-ld=yes --target=i686-elf --disable-werror --enable-silent-rules`.

Do anyone have a solution to this? Is it possible to create a custom formula just for IncludeOS? Or should we just keep doing as we do it?

**Comment by shekhar108** [comment]
The utilities we need are for i686 arch and package managers (mainly brew and macports) cannot install tools for other arch. 
I think it is best to stick with what we have now.

**Comment by AndreasAakesson** [comment]
Thanks for input! Yes, it currently works ok as we have it so we'll stick with it for now.

**Comment by AndreasAakesson** [comment]
Leave it as it is for now.
