### ISSUE TITLE
Installing in Fedora 24

### ISSUE THREAD

**Issue by TheTelematic** [hioa-cs/IncludeOS#883]
Hi everybody,
First, congratulations for the job, it's a awesome project.

Second,
**I'm trying to install it in Fedora but when I run "install.sh" , said that "lsb_release" doesn't exist.**

(I appreciate you answer me because I want to do my final project of my university degree using your library).

Cheers.
![includeos-install](https://cloud.githubusercontent.com/assets/20907688/19419801/9acd5b5e-93df-11e6-99a6-4f4d6a68402d.png)

**Comment by TheTelematic** [comment]
If it was better that I develop in Ubuntu, said me, (to switch to Ubuntu before I start with my project :D )

**Comment by rianquinn** [comment]
@TheTelematic Did you try:

```
yum install redhat-lsb
```

On a side note, we have a similar issue with OpenSUSE and are working to change our scripts to use `/etc/os-release` as seen [here](https://github.com/Bareflank/hypervisor/issues/139)

**Comment by TheTelematic** [comment]
It works!
Thank you very much :D
(PS: Awesome, the test consumes only 252KB)
