### ISSUE TITLE
Incomplete instructions at end of install.sh when running on OS X

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#884]
After installing IncludeOS by running ./install.sh, the script outputs information that the user should follow when building services, running tests and rebuilding IncludeOS: 

```
>>> Done! IncludeOS bundle downloaded and installed

### OS X installation done. ###

To build services and run tests, set LD_INC and STRIP_INC:
export LD_INC=/Users/ingve/IncludeOS_install/bin/ld && export STRIP_INC=/Users/ingve/IncludeOS_install/bin/strip

To rebuild IncludeOS, set AR_INC and OBJCOPY_INC (in addtion to the above):
export AR_INC=/Users/ingve/IncludeOS_install/bin/ar && export OBJCOPY_INC=/Users/ingve/IncludeOS_install/bin/objcopy

To run services, see: ./etc/vboxrun.sh. (VirtualBox needs to be installed)
```

If you follow these instructions when building a service, you get an error message:

```
objcopy --update-section .elf_symbols=_elf_symbols.bin 256_Color_VGA 256_Color_VGA
make: objcopy: No such file or directory
make: *** [service] Error 1
```

Exporting OBJCOPY_INC and re-running make fixes the issue, so it would appear that `objcopy` is not just required when rebuilding IncludeOS, it is also required when building services and running tests.

**Comment by alfred-bratterud** [comment]
Great, please PR :-)
