### ISSUE TITLE
Error installing: could not install build requirements for Ubuntu Mint 

### ISSUE THREAD

**Issue by carlosb1** [hioa-cs/IncludeOS#929]
I downloaded the master repository and I typed the "./install.sh" command and I receive:
➜  IncludeOS git:(ec51938) ./install.sh Linux LinuxMint
-e >>> Sorry <<< 
Could not install build requirements. 

My OS is a Linux Mint is a :

DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"

**Comment by fwsGonzo** [comment]
Does it work now, @carlosb1 ?

**Comment by RicoAntonioFelix** [comment]
Test result on Linux Mint 18 shown in the attached screenshot...
![screenshot from 2016-11-10 13-35-29](https://cloud.githubusercontent.com/assets/6290785/20187444/a3beb9a0-a74a-11e6-9d20-d5ba9c9890a8.png)

**Comment by carlosb1** [comment]
@fwsGonzo  I had tried o install it with the master branch, I watched you did the pull request in dev...Currenty, I have the same problem in master, but I changed to dev and It started to compile the project but. I received another error: 
![error_includeos](https://cloud.githubusercontent.com/assets/1107703/20191778/4b1ae4bc-a787-11e6-8ce0-8d0e378b2b2d.png)

**Comment by fwsGonzo** [comment]
That happens to me when im building with parallell make (make -j) on the cmake build. Is this normal makefile? It kinda looks like old clang or old GSL or something.

**Comment by carlosb1** [comment]
I don't know if I got what are trying to explain me exactly, but yes, it seems a normal make (with clang!)
If i check the build, it is compiling with clang

```
cp -r ../seed /home/carlos/IncludeOS_install
mkdir -p /home/carlos/IncludeOS_install/mod/
cp -r ../mod/GSL /home/carlos/IncludeOS_install/mod

Done!
~/c-workspace/IncludeOS


>>> Compiling the vmbuilder, which makes a bootable vm out of your service
~/c-workspace/IncludeOS/vmbuild ~/c-workspace/IncludeOS
/usr/bin/clang++-3.8 -std=c++14 -c -Wall -Wextra -O2 -I/home/carlos/IncludeOS_install/api -I/home/carlos/IncludeOS_install/mod/GSL vmbuild.cpp -o vmbuild.o
In file included from vmbuild.cpp:19:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/fstream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/istream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ios:42:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/ios_base.h:41:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/locale_classes.h:40:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global
      namespace
  using ::gets;
        ~~^
```

**Comment by carlosb1** [comment]
I checked the install.sh. It calls the install_from_bundle.sh script which It does: echo -e "\n\n>>> Building IncludeOS"
pushd $INCLUDEOS_SRC/src
**make -j2**
make install
popd

It is applying the -j flag... Would I remove it?

**Comment by FatihBAKIR** [comment]
@carlosb1, the last error message you posted is in my experience results from clang trying to use libstdc++. Do yo have `libc++-dev` installed?
