### ISSUE TITLE
missing cxxabi.h

### ISSUE THREAD

**Issue by hartsantler** [hioa-cs/IncludeOS#945]
I would like to use the Cereal library with IncludeOS, but Cereal requires `cxxabi.h`, included from: `cereal/details/util.hpp`.  Other unikernels like OSV provide, cxxabi.h, maybe its implementation could be used as a starting point for porting to IncludeOS?

**Comment by fwsGonzo** [comment]
Will look into it next week :+1:

**Comment by fwsGonzo** [comment]
The file is in `src/include/cxxabi.h`, you could try copying it to the location where you need it?
