### ISSUE TITLE
Error when executing ./test.sh on macos (El Capitan)

### ISSUE THREAD

**Issue by pedromsantos** [hioa-cs/IncludeOS#947]
$ ./test.sh
~/src/IncludeOS/examples/demo_service ~/src/IncludeOS

>> Linking service with OS
/Users/pedros/IncludeOS_install/bin/ld -nostdlib -melf_i386 -N --eh-frame-hdr --script=/Users/pedros/IncludeOS_install/linker.ld --defsym _MAX_MEM_MIB_=128 --defsym=__stack_rand_ba=`date +%s` --strip-debug /Users/pedros/IncludeOS_install/crt/crtbegin.o /Users/pedros/IncludeOS_install/crt/crti.o /Users/pedros/IncludeOS_install/multiboot.o service.o .service_name.o /Users/pedros/IncludeOS_install/drivers/virtionet.o   /Users/pedros/IncludeOS_install/os.a /Users/pedros/IncludeOS_install/libcxx/libc++.a /Users/pedros/IncludeOS_install/libcxx/libc++abi.a /Users/pedros/IncludeOS_install/os.a /Users/pedros/IncludeOS_install/newlib/libc.a /Users/pedros/IncludeOS_install/newlib/libm.a /Users/pedros/IncludeOS_install/libgcc/libgcc.a /Users/pedros/IncludeOS_install/crt/crtend.o /Users/pedros/IncludeOS_install/crt/crtn.o  -o Demo_Service

>> Adding symbol section
/Users/pedros/IncludeOS_install/elf_syms Demo_Service
objcopy --update-section .elf_symbols=_elf_symbols.bin Demo_Service Demo_Service
make: objcopy: No such file or directory
make: *** [service] Error 1

INSTALL FAILED ON COMMAND: make

**Comment by ingve** [comment]
Hi, thanks for trying IncludeOS! Seems like make cannot find the version of objcopy that is installed by the install script.

After getting this error, what is the output of `echo $OBJCOPY_INC` in the Terminal window you ran test.sh from?

**Comment by pedromsantos** [comment]
Hi, the output of echo $OBJCOPY_INC is empty

**Comment by ingve** [comment]
At the end of the install script, when running on OS X, there should be some instructions printed about environment variables that need to be set, and the correct value for OBJCOPY_INC should be printed. Could you try test.sh again after setting OBJCOPY_INC?
