### ISSUE TITLE
Refactor IP4- & Eth addr integration tests to unit tests

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#965]
`test/net/integration/ipv4` and `test/net/integration/ethernet` do not use any IncludeOS internals and can easily be tested with unit tests (`net/ip4/addr.hpp` and `net/hw/mac_addr.hpp`).

**Comment by ingve** [comment]
Many of the test cases in `test/net/integration/ipv4` seem to be covered already by `test/net/unit/ip4_addr.cpp` (valid IP4 address, invalid numeric address parts (above 255), and totally bogus string). Seems like only the extraneous whitespace case is not covered by the unit tests.

**Comment by ingve** [comment]
Not-already-covered test cases from the mentioned integration tests have been added as normal unit tests in https://github.com/hioa-cs/IncludeOS/pull/939/commits/a062ff7cf6aa5da6994aa8861c26246decda74ee and https://github.com/hioa-cs/IncludeOS/pull/939/commits/94ba703ca496df6c52254a6e511aee43204c6ac4

**Comment by AndreasAakesson** [comment]
Nice 👍  Just remove the integration tests then imo.
