### ISSUE TITLE
Failed tests does not cleanup

### ISSUE THREAD

**Issue by AndreasAakesson** [hioa-cs/IncludeOS#967]
When I run `test/test.py` there is some tests failing due to missing lest (#966) and running on Mac (linux specific commands #932). These all leave an unfinished build `<test>/build`. I guess this is not an issue when working on a single test, but it's a lot of work to clean up every failed test.

Should every test clean up on exit?
Or maybe have the root test.py clean up every test recursively (with supplied arg or when done)?

**Comment by alfred-bratterud** [comment]
There's an option `./test.py -c` that will clean up each test before running a second time.

**Comment by AndreasAakesson** [comment]
Thanks! Tho I guess this will end up with the same result since the test is ran once again. I guess I can add a second option for just cleaning, or some flag that breaks after the cleaning is done. Any suggestions?
