### ISSUE TITLE
[fixed] ACPI shutdown fail when using Serial

### ISSUE THREAD

**Issue by Voultapher** [hioa-cs/IncludeOS#987]
This code **sometimes** results in ACPI shutdown failure.

```cpp
#include <os>
#include <hw/serial.hpp>
#include <timers>

void Service::start(const std::string&)
{
	auto& com = hw::Serial::port<1>();

	Timers::oneshot(std::chrono::seconds(3),
		[](auto) -> void { OS::shutdown(); }
	);
}
```

**Comment by fwsGonzo** [comment]
Have you checked if the Serial object here isn't being optimized away?

**Comment by Voultapher** [comment]
`volatile auto& com = hw::Serial::port<1>();` does the same.
And just `OS::shutdown` did never fail.

**Comment by gurka** [comment]
Has this been fixed? I'm not able to reproduce it on IncludeOS v0.10.0-rc.1-9-g151a2b9.

What exactly did you mean with "ACPI shutdown fail"?  Did you get some kind of error message or was the machine not just shutting down?

**Comment by Voultapher** [comment]
It printed "ACPI shutdown fail" [relevant code](https://github.com/hioa-cs/IncludeOS/blob/dev/src/hw/acpi.cpp#L358)

Although this example may not fail anymore, it still occurs on other occasions.

**Comment by fwsGonzo** [comment]
Is this still happening?

**Comment by Voultapher** [comment]
Seems to be fixed.

**Comment by Voultapher** [comment]
Can we tag it as fixed and then close it.

**Comment by fwsGonzo** [comment]
Not sure how to tag something as fixed, but it has to have been happening because of something else... Closing :P
