### ISSUE TITLE
Build documentation missing.

### ISSUE THREAD

**Issue by qis** [hioa-cs/IncludeOS#989]
Currently there are no instructions on how to build IncludeOS. Calling `install.sh --all-source` does not really count since it locks you into a specific compiler version and does no work on Ubuntu 16.04.1 WSL.

**Comment by ingve** [comment]
Thank you for trying IncludeOS! We are migrating to a CMake-based build system, you can try it out if you check out the `dev` branch. 

What happens when you install on Ubuntu 16.04.1 WSL? Any details (logs, error messages etc) you could provide would be very helpful.

**Comment by qis** [comment]
@ingve The problem with WSL right now is that `apt-get install` displays an error message and returns a non-zero value after a successful installation. If you're migrating to CMake, I'd rather use that. Will try it out after work.

**Comment by fwsGonzo** [comment]
CMake support is complete now, so closing this
